# =============================================================================
# quizsets.py  --  THE TOPIC QUIZ QUESTION SETS, PINNED  --  Hyperion Shift LLC
# -----------------------------------------------------------------------------
# CHANGE NOTES (keep newest at top):
#   2026-08-27  NEW FILE (build ov -- QUIZZES THROUGH THE AUTHORED SPINE).
#               GENERATED, then committed as data on purpose. Two reasons, and
#               both are load-bearing:
#
#               ⭐ THE AUDIO CLOSURE MUST BE INSTANT AND STABLE. Every sentence
#               the app can speak in Mr. Cadabra's voice is enumerated in advance
#               and rendered once (lessonscripts.course_audio_lines). Computing
#               the quiz questions from drillpool.pool_for at call time made that
#               enumeration take MINUTES -- one lesson alone measured 14 seconds
#               -- which would have broken /admin's prewarm price button. Worse,
#               it would have made the closure a moving target: any future tweak
#               to the pool scan would silently invalidate audio already paid for.
#               Pinned questions cannot drift from pinned audio.
#
#               ⭐ AN ASSESSMENT SHOULD BE REVIEWABLE. These are the questions
#               every child is graded on. As data they can be read, argued with,
#               and changed deliberately, instead of being whatever an algorithm
#               happened to emit on the day.
#
#               HOW THEY WERE CHOSEN: drillpool.quiz_problems -- spaced evenly
#               across the lesson's ramped pool of extra problems (never its easy
#               end), each already through lessonscripts.validate(), topped up
#               from the bank's tail for the 73 lessons whose ops admit too few
#               extras. REGENERATE with tools/genquiz.py after any change to a
#               lesson's bank, its op, or the pool scan -- and re-run the prewarm,
#               because a changed question is a new sentence to render.
# =============================================================================

QUIZ_SETS = {
    'entry-u1-counting-to-10': [
        {"op": 'cnt', "a": 10, "b": 0},
        {"op": 'cnt', "a": 9, "b": 0},
        {"op": 'cnt', "a": 8, "b": 0},
        {"op": 'cnt', "a": 7, "b": 0},
        {"op": 'cnt', "a": 6, "b": 0},
    ],
    'entry-u1-numbers-before-and-after': [
        {"op": 'aft', "a": 1, "b": 0, "c": 0},
        {"op": 'aft', "a": 6, "b": 0, "c": 0},
        {"op": 'aft', "a": 10, "b": 0, "c": 0},
        {"op": 'aft', "a": 13, "b": 0, "c": 0},
        {"op": 'aft', "a": 16, "b": 0, "c": 0},
    ],
    'entry-u2-add-single-digit': [
        {"op": '+', "a": 1, "b": 1, "c": 0},
        {"op": '+', "a": 5, "b": 1, "c": 0},
        {"op": '+', "a": 2, "b": 6, "c": 0},
        {"op": '+', "a": 2, "b": 7, "c": 0},
        {"op": '+', "a": 3, "b": 7, "c": 0},
    ],
    'entry-u2-add-past-ten': [
        {"op": '+', "a": 1, "b": 1, "c": 0},
        {"op": '+', "a": 4, "b": 2, "c": 0},
        {"op": '+', "a": 6, "b": 2, "c": 0},
        {"op": '+', "a": 5, "b": 5, "c": 0},
        {"op": '+', "a": 5, "b": 7, "c": 0},
    ],
    'entry-u3-take-away-single-digit': [
        {"op": '-', "a": 2, "b": 1, "c": 0},
        {"op": '-', "a": 6, "b": 5, "c": 0},
        {"op": '-', "a": 7, "b": 3, "c": 0},
        {"op": '-', "a": 8, "b": 4, "c": 0},
        {"op": '-', "a": 9, "b": 7, "c": 0},
    ],
    'entry-u3-take-away-bigger': [
        {"op": '-', "a": 2, "b": 1, "c": 0},
        {"op": '-', "a": 8, "b": 6, "c": 0},
        {"op": '-', "a": 10, "b": 1, "c": 0},
        {"op": '-', "a": 14, "b": 8, "c": 0},
        {"op": '-', "a": 17, "b": 7, "c": 0},
    ],
    'entry-u3-story-problems': [
        {"op": '+', "a": 1, "b": 1, "c": 0},
        {"op": '+', "a": 1, "b": 5, "c": 0},
        {"op": '+', "a": 6, "b": 1, "c": 0},
        {"op": '+', "a": 1, "b": 8, "c": 0},
        {"op": '+', "a": 2, "b": 8, "c": 0},
    ],
    'entry-u4-tens-and-ones': [
        {"op": 't', "a": 1, "b": 9},
        {"op": 't', "a": 1, "b": 8},
        {"op": 't', "a": 1, "b": 7},
        {"op": 't', "a": 1, "b": 6},
        {"op": 't', "a": 1, "b": 4},
    ],
    'entry-u5-add-two-digit-no-carry': [
        {"op": '+', "a": 1, "b": 1, "c": 0},
        {"op": '+', "a": 1, "b": 20, "c": 0},
        {"op": '+', "a": 1, "b": 40, "c": 0},
        {"op": '+', "a": 1, "b": 60, "c": 0},
        {"op": '+', "a": 1, "b": 80, "c": 0},
    ],
    'entry-u5-add-with-carrying': [
        {"op": '+', "a": 1, "b": 9, "c": 0},
        {"op": '+', "a": 6, "b": 17, "c": 0},
        {"op": '+', "a": 7, "b": 34, "c": 0},
        {"op": '+', "a": 5, "b": 55, "c": 0},
        {"op": '+', "a": 7, "b": 67, "c": 0},
    ],
    'entry-u6-take-away-with-regrouping': [
        {"op": '-', "a": 10, "b": 9, "c": 0},
        {"op": '-', "a": 20, "b": 16, "c": 0},
        {"op": '-', "a": 23, "b": 15, "c": 0},
        {"op": '-', "a": 30, "b": 18, "c": 0},
        {"op": '-', "a": 32, "b": 19, "c": 0},
    ],
    'entry-u7-counting-coins': [
        {"op": 'nick', "a": 1, "b": 2, "c": 0},
        {"op": 'nick', "a": 2, "b": 3, "c": 0},
        {"op": 'nick', "a": 3, "b": 4, "c": 0},
        {"op": 'nick', "a": 4, "b": 4, "c": 0},
        {"op": 'nick', "a": 5, "b": 3, "c": 0},
    ],
    'entry-u8-later-on-the-clock': [
        {"op": 'hrl', "a": 1, "b": 2, "c": 0},
        {"op": 'hrl', "a": 2, "b": 3, "c": 0},
        {"op": 'hrl', "a": 3, "b": 4, "c": 0},
        {"op": 'hrl', "a": 6, "b": 2, "c": 0},
        {"op": 'hrl', "a": 8, "b": 1, "c": 0},
    ],
    'entry-u8-minutes-past-the-hour': [
        {"op": 'min5', "a": 3, "b": 0, "c": 0},
        {"op": 'min5', "a": 4, "b": 0, "c": 0},
        {"op": 'min5', "a": 6, "b": 0, "c": 0},
        {"op": 'min5', "a": 9, "b": 0, "c": 0},
        {"op": 'min5', "a": 8, "b": 0},
    ],
    'entry-u8-weeks-and-days': [
        {"op": 'dwd', "a": 1, "b": 6, "c": 0},
        {"op": 'dwd', "a": 2, "b": 2, "c": 0},
        {"op": 'dwd', "a": 3, "b": 2, "c": 0},
        {"op": 'dwd', "a": 3, "b": 5, "c": 0},
        {"op": 'dwd', "a": 4, "b": 3, "c": 0},
    ],
    'entry-u8-how-much-longer': [
        {"op": 'cube', "a": 4, "b": 2, "c": 0},
        {"op": 'cube', "a": 8, "b": 5, "c": 0},
        {"op": 'cube', "a": 10, "b": 6, "c": 0},
        {"op": 'cube', "a": 11, "b": 1, "c": 0},
        {"op": 'cube', "a": 13, "b": 3, "c": 0},
    ],
    'entry-u9-sides-and-corners': [
        {"op": 'cor', "a": 10, "b": 0},
        {"op": 'cor', "a": 8, "b": 0},
        {"op": 'cor', "a": 7, "b": 0},
        {"op": 'cor', "a": 6, "b": 0},
    ],
    'entry-u9-what-comes-next': [
        {"op": 'pat', "a": 6, "b": 1, "c": 0},
        {"op": 'pat', "a": 4, "b": 2, "c": 0},
        {"op": 'pat', "a": 2, "b": 3, "c": 0},
        {"op": 'pat', "a": 9, "b": 3, "c": 0},
        {"op": 'pat', "a": 5, "b": 4, "c": 0},
    ],
    'entry-u9-equal-groups': [
        {"op": 'grp', "a": 4, "b": 2, "c": 0},
        {"op": 'grp', "a": 2, "b": 5, "c": 0},
        {"op": 'grp', "a": 5, "b": 2, "c": 0},
        {"op": 'grp', "a": 3, "b": 5, "c": 0},
        {"op": 'grp', "a": 5, "b": 4, "c": 0},
    ],
    'entry-u9-sharing-fairly': [
        {"op": 'eqs', "a": 12, "b": 4, "c": 0},
        {"op": 'eqs', "a": 12, "b": 2, "c": 0},
        {"op": 'eqs', "a": 15, "b": 5, "c": 0},
        {"op": 'eqs', "a": 20, "b": 5, "c": 0},
        {"op": 'eqs', "a": 20, "b": 4, "c": 0},
    ],
    'basic-u1-place-value-to-1000': [
        {"op": 'pv', "a": 1, "b": 1, "c": 3},
        {"op": 'pv', "a": 1, "b": 6, "c": 7},
        {"op": 'pv', "a": 2, "b": 4, "c": 3},
        {"op": 'pv', "a": 3, "b": 1, "c": 7},
        {"op": 'pv', "a": 3, "b": 7, "c": 2},
    ],
    'basic-u1-rounding-tens': [
        {"op": 'r10', "a": 11, "b": 0, "c": 0},
        {"op": 'r10', "a": 27, "b": 0, "c": 0},
        {"op": 'r10', "a": 44, "b": 0, "c": 0},
        {"op": 'r10', "a": 61, "b": 0, "c": 0},
        {"op": 'r10', "a": 77, "b": 0, "c": 0},
    ],
    'basic-u1-rounding-hundreds': [
        {"op": 'r100', "a": 101, "b": 0, "c": 0},
        {"op": 'r100', "a": 150, "b": 0, "c": 0},
        {"op": 'r100', "a": 199, "b": 0, "c": 0},
        {"op": 'r100', "a": 249, "b": 0, "c": 0},
        {"op": 'r100', "a": 298, "b": 0, "c": 0},
    ],
    'basic-u1-multi-digit-review': [
        {"op": '+', "a": 1, "b": 1, "c": 0},
        {"op": '+', "a": 1, "b": 18, "c": 0},
        {"op": '+', "a": 1, "b": 34, "c": 0},
        {"op": '+', "a": 1, "b": 51, "c": 0},
        {"op": '+', "a": 1, "b": 75, "c": 0},
    ],
    'basic-u2-what-multiplying-means': [
        {"op": '*', "a": 5, "b": 5},
        {"op": '*', "a": 4, "b": 5},
        {"op": '*', "a": 3, "b": 5},
        {"op": '*', "a": 4, "b": 4},
        {"op": '*', "a": 2, "b": 5},
    ],
    'basic-u2-times-tables': [
        {"op": '*', "a": 2, "b": 9, "c": 0},
        {"op": '*', "a": 7, "b": 3, "c": 0},
        {"op": '*', "a": 4, "b": 7, "c": 0},
        {"op": '*', "a": 7, "b": 5, "c": 0},
        {"op": '*', "a": 6, "b": 8, "c": 0},
    ],
    'basic-u2-multiply-two-digit': [
        {"op": '*', "a": 6, "b": 4, "c": 0},
        {"op": '*', "a": 9, "b": 5, "c": 0},
        {"op": '*', "a": 23, "b": 3, "c": 0},
        {"op": '*', "a": 54, "b": 2, "c": 0},
        {"op": '*', "a": 32, "b": 5, "c": 0},
    ],
    'basic-u3-what-dividing-means': [
        {"op": '/', "a": 10, "b": 2, "c": 0},
        {"op": '/', "a": 15, "b": 5, "c": 0},
        {"op": '/', "a": 21, "b": 3, "c": 0},
        {"op": '/', "a": 27, "b": 9, "c": 0},
        {"op": '/', "a": 35, "b": 5, "c": 0},
    ],
    'basic-u3-left-overs': [
        {"op": 'rem', "a": 1, "b": 2, "c": 0},
        {"op": 'rem', "a": 7, "b": 4, "c": 0},
        {"op": 'rem', "a": 16, "b": 5, "c": 0},
        {"op": 'rem', "a": 23, "b": 4, "c": 0},
        {"op": 'rem', "a": 31, "b": 6, "c": 0},
    ],
    'basic-u3-divide-two-digit': [
        {"op": '/', "a": 24, "b": 2, "c": 0},
        {"op": '/', "a": 42, "b": 2, "c": 0},
        {"op": '/', "a": 56, "b": 4, "c": 0},
        {"op": '/', "a": 64, "b": 2, "c": 0},
        {"op": '/', "a": 78, "b": 3, "c": 0},
    ],
    'basic-u3-story-problems': [
        {"op": '*', "a": 1, "b": 2, "c": 0},
        {"op": '*', "a": 3, "b": 2, "c": 0},
        {"op": '*', "a": 2, "b": 6, "c": 0},
        {"op": '*', "a": 8, "b": 2, "c": 0},
        {"op": '*', "a": 10, "b": 2, "c": 0},
    ],
    'basic-u4-missing-factors': [
        {"op": 'mf', "a": 8, "b": 2, "c": 0},
        {"op": 'mf', "a": 18, "b": 6, "c": 0},
        {"op": 'mf', "a": 24, "b": 3, "c": 0},
        {"op": 'mf', "a": 32, "b": 4, "c": 0},
        {"op": 'mf', "a": 45, "b": 5, "c": 0},
    ],
    'basic-u4-greatest-common-factor': [
        {"op": 'gcf', "a": 2, "b": 0, "c": 0},
        {"op": 'gcf', "a": 12, "b": 10, "c": 0},
        {"op": 'gcf', "a": 12, "b": 18, "c": 0},
        {"op": 'gcf', "a": 4, "b": 28, "c": 0},
        {"op": 'gcf', "a": 3, "b": 39, "c": 0},
    ],
    'basic-u4-least-common-multiple': [
        {"op": 'lcm', "a": 4, "b": 2, "c": 0},
        {"op": 'lcm', "a": 6, "b": 2, "c": 0},
        {"op": 'lcm', "a": 2, "b": 5, "c": 0},
        {"op": 'lcm', "a": 5, "b": 3, "c": 0},
        {"op": 'lcm', "a": 6, "b": 8, "c": 0},
    ],
    'basic-u5-fractions-on-the-number-line': [
        {"op": 'nl', "a": 1, "b": 4, "c": 0},
        {"op": 'nl', "a": 3, "b": 6, "c": 0},
        {"op": 'nl', "a": 4, "b": 7, "c": 0},
        {"op": 'nl', "a": 5, "b": 8, "c": 0},
        {"op": 'nl', "a": 5, "b": 9, "c": 0},
    ],
    'basic-u5-fraction-of-a-group': [
        {"op": 'of', "a": 8, "b": 2, "c": 0},
        {"op": 'of', "a": 10, "b": 5, "c": 0},
        {"op": 'of', "a": 12, "b": 4, "c": 0},
        {"op": 'of', "a": 18, "b": 6, "c": 0},
        {"op": 'of', "a": 20, "b": 4, "c": 0},
    ],
    'basic-u5-equivalent-fractions': [
        {"op": 'eqf', "a": 1, "b": 2, "c": 12},
        {"op": 'eqf', "a": 1, "b": 3, "c": 12},
        {"op": 'eqf', "a": 1, "b": 4, "c": 12},
        {"op": 'eqf', "a": 1, "b": 6, "c": 12},
        {"op": 'eqf', "a": 1, "b": 5, "c": 10},
    ],
    'basic-u6-add-fractions-same-bottom': [
        {"op": 'fa', "a": 1, "b": 1, "c": 3},
        {"op": 'fa', "a": 2, "b": 1, "c": 5},
        {"op": 'fa', "a": 3, "b": 1, "c": 5},
        {"op": 'fa', "a": 4, "b": 1, "c": 6},
        {"op": 'fa', "a": 5, "b": 1, "c": 8},
    ],
    'basic-u6-take-away-fractions-same-bottom': [
        {"op": 'fs', "a": 2, "b": 0, "c": 3},
        {"op": 'fs', "a": 3, "b": 0, "c": 12},
        {"op": 'fs', "a": 5, "b": 3, "c": 12},
        {"op": 'fs', "a": 6, "b": 2, "c": 10},
        {"op": 'fs', "a": 7, "b": 2, "c": 12},
    ],
    'basic-u6-add-fractions-different-bottoms': [
        {"op": 'fu', "a": 2, "b": 2, "c": 6},
        {"op": 'fu', "a": 2, "b": 5, "c": 10},
        {"op": 'fu', "a": 7, "b": 5, "c": 10},
        {"op": 'fu', "a": 3, "b": 4, "c": 12},
        {"op": 'fu', "a": 4, "b": 3, "c": 12},
    ],
    'basic-u7-tenths': [
        {"op": 'dt', "a": 2, "b": 1, "c": 0},
        {"op": 'dt', "a": 2, "b": 3, "c": 0},
        {"op": 'dt', "a": 1, "b": 5, "c": 0},
        {"op": 'dt', "a": 3, "b": 4, "c": 0},
        {"op": 'dt', "a": 7, "b": 0, "c": 0},
    ],
    'basic-u7-dimes-and-pennies': [
        {"op": 'm', "a": 1, "b": 3, "c": 0},
        {"op": 'm', "a": 3, "b": 2, "c": 0},
        {"op": 'm', "a": 4, "b": 9, "c": 0},
        {"op": 'm', "a": 6, "b": 6, "c": 0},
        {"op": 'm', "a": 8, "b": 3, "c": 0},
    ],
    'basic-u7-hundredths': [
        {"op": 'dh', "a": 10, "b": 13, "c": 0},
        {"op": 'dh', "a": 12, "b": 18, "c": 0},
        {"op": 'dh', "a": 15, "b": 20, "c": 0},
        {"op": 'dh', "a": 18, "b": 22, "c": 0},
        {"op": 'dh', "a": 12, "b": 34, "c": 0},
    ],
    'basic-u8-percent-of': [
        {"op": 'pc', "a": 20, "b": 5, "c": 0},
        {"op": 'pc', "a": 20, "b": 15, "c": 0},
        {"op": 'pc', "a": 45, "b": 20, "c": 0},
        {"op": 'pc', "a": 36, "b": 25, "c": 0},
        {"op": 'pc', "a": 20, "b": 40, "c": 0},
    ],
    'basic-u8-one-costs': [
        {"op": 'rate', "a": 4, "b": 2, "c": 0},
        {"op": 'rate', "a": 9, "b": 3, "c": 0},
        {"op": 'rate', "a": 15, "b": 5, "c": 0},
        {"op": 'rate', "a": 18, "b": 6, "c": 0},
        {"op": 'rate', "a": 25, "b": 5, "c": 0},
    ],
    'basic-u9-perimeter': [
        {"op": 'peri', "a": 4, "b": 1, "c": 0},
        {"op": 'peri', "a": 7, "b": 3, "c": 0},
        {"op": 'peri', "a": 9, "b": 3, "c": 0},
        {"op": 'peri', "a": 10, "b": 4, "c": 0},
        {"op": 'peri', "a": 11, "b": 5, "c": 0},
    ],
    'basic-u9-area': [
        {"op": 'area', "a": 6, "b": 1, "c": 0},
        {"op": 'area', "a": 12, "b": 1, "c": 0},
        {"op": 'area', "a": 9, "b": 3, "c": 0},
        {"op": 'area', "a": 10, "b": 4, "c": 0},
        {"op": 'area', "a": 12, "b": 5, "c": 0},
    ],
    'basic-u9-quarter-turns': [
        {"op": 'angq', "a": 270, "b": 0},
        {"op": 'ang', "a": 3, "b": 0},
        {"op": 'angq', "a": 180, "b": 0},
        {"op": 'ang', "a": 2, "b": 0},
        {"op": 'angq', "a": 90, "b": 0},
    ],
    'basic-u9-volume': [
        {"op": 'vol', "a": 1, "b": 1, "c": 4},
        {"op": 'vol', "a": 1, "b": 4, "c": 2},
        {"op": 'vol', "a": 3, "b": 1, "c": 4},
        {"op": 'vol', "a": 4, "b": 4, "c": 1},
        {"op": 'vol', "a": 5, "b": 2, "c": 3},
    ],
    'pre-u1-times-before-add': [
        {"op": 'tba', "a": 3, "b": 2, "c": 2},
        {"op": 'tba', "a": 5, "b": 7, "c": 2},
        {"op": 'tba', "a": 1, "b": 4, "c": 6},
        {"op": 'tba', "a": 2, "b": 4, "c": 8},
        {"op": 'tba', "a": 2, "b": 5, "c": 9},
    ],
    'pre-u1-parentheses-first': [
        {"op": 'parf', "a": 2, "b": 1, "c": 2},
        {"op": 'parf', "a": 1, "b": 3, "c": 5},
        {"op": 'parf', "a": 1, "b": 9, "c": 3},
        {"op": 'parf', "a": 5, "b": 3, "c": 5},
        {"op": 'parf', "a": 4, "b": 3, "c": 8},
    ],
    'pre-u1-exponents-are-repeated-times': [
        {"op": 'expn', "a": 3, "b": 3, "c": 0},
        {"op": 'expn', "a": 6, "b": 3},
        {"op": 'expn', "a": 5, "b": 3},
        {"op": 'expn', "a": 9, "b": 2},
        {"op": 'expn', "a": 8, "b": 2},
    ],
    'pre-u1-power-then-times-then-add': [
        {"op": 'exo', "a": 3, "b": 2, "c": 3},
        {"op": 'exo', "a": 4, "b": 2, "c": 5},
        {"op": 'exo', "a": 5, "b": 4, "c": 2},
        {"op": 'exo', "a": 5, "b": 4, "c": 4},
        {"op": 'exo', "a": 6, "b": 4, "c": 4},
    ],
    'pre-u2-how-many-factors': [
        {"op": 'nfac', "a": 4, "b": 0, "c": 0},
        {"op": 'nfac', "a": 9, "b": 2, "c": 0},
        {"op": 'nfac', "a": 14, "b": 7, "c": 0},
        {"op": 'nfac', "a": 20, "b": 2, "c": 0},
        {"op": 'nfac', "a": 25, "b": 6, "c": 0},
    ],
    'pre-u2-the-smallest-factor': [
        {"op": 'spf', "a": 9, "b": 0, "c": 0},
        {"op": 'spf', "a": 25, "b": 6, "c": 0},
        {"op": 'spf', "a": 39, "b": 2, "c": 0},
        {"op": 'spf', "a": 55, "b": 0, "c": 0},
        {"op": 'spf', "a": 65, "b": 3, "c": 0},
    ],
    'pre-u2-breaking-into-primes': [
        {"op": 'npf', "a": 4, "b": 0, "c": 0},
        {"op": 'npf', "a": 16, "b": 3, "c": 0},
        {"op": 'npf', "a": 28, "b": 2, "c": 0},
        {"op": 'npf', "a": 40, "b": 2, "c": 0},
        {"op": 'npf', "a": 52, "b": 4, "c": 0},
    ],
    'pre-u3-counting-back-past-zero': [
        {"op": 'cbz', "a": 5, "b": 18},
        {"op": 'cbz', "a": 2, "b": 14},
        {"op": 'cbz', "a": 8, "b": 19},
        {"op": 'cbz', "a": 7, "b": 16},
        {"op": 'cbz', "a": 3, "b": 12},
    ],
    'pre-u3-adding-a-negative': [
        {"op": 'addneg', "a": 5, "b": 21},
        {"op": 'addneg', "a": 3, "b": 16},
        {"op": 'addneg', "a": 7, "b": 18},
        {"op": 'addneg', "a": 2, "b": 11},
        {"op": 'addneg', "a": 6, "b": 14},
    ],
    'pre-u3-taking-away-a-negative': [
        {"op": 'subneg', "a": 3, "b": 2, "c": 0},
        {"op": 'subneg', "a": 4, "b": 5, "c": 0},
        {"op": 'subneg', "a": 3, "b": 9, "c": 0},
        {"op": 'subneg', "a": 5, "b": 10, "c": 0},
        {"op": 'subneg', "a": 8, "b": 10, "c": 0},
    ],
    'pre-u3-times-with-a-negative': [
        {"op": 'mulneg', "a": 9, "b": 9},
        {"op": 'mulneg', "a": 7, "b": 8},
        {"op": 'mulneg', "a": 6, "b": 7},
        {"op": 'mulneg', "a": 4, "b": 8},
        {"op": 'mulneg', "a": 5, "b": 5},
    ],
    'pre-u4-a-fraction-of-a-number': [
        {"op": 'nuf', "a": 2, "b": 4, "c": 8},
        {"op": 'nuf', "a": 4, "b": 8, "c": 8},
        {"op": 'nuf', "a": 3, "b": 6, "c": 12},
        {"op": 'nuf', "a": 4, "b": 7, "c": 14},
        {"op": 'nuf', "a": 3, "b": 5, "c": 20},
    ],
    'pre-u4-how-many-parts-in-a-whole': [
        {"op": 'uic', "a": 4, "b": 2, "c": 0},
        {"op": 'uic', "a": 4, "b": 3, "c": 0},
        {"op": 'uic', "a": 8, "b": 2, "c": 0},
        {"op": 'uic', "a": 8, "b": 3, "c": 0},
        {"op": 'uic', "a": 5, "b": 7, "c": 0},
    ],
    'pre-u4-dividing-by-a-fraction': [
        {"op": 'dbf', "a": 2, "b": 4, "c": 4},
        {"op": 'dbf', "a": 2, "b": 7, "c": 4},
        {"op": 'dbf', "a": 4, "b": 8, "c": 8},
        {"op": 'dbf', "a": 5, "b": 9, "c": 10},
        {"op": 'dbf', "a": 4, "b": 8, "c": 11},
    ],
    'pre-u4-fractions-bigger-than-one': [
        {"op": 'imp', "a": 13, "b": 6, "c": 0},
        {"op": 'imp', "a": 11, "b": 3, "c": 0},
        {"op": 'imp', "a": 23, "b": 6, "c": 0},
        {"op": 'imp', "a": 13, "b": 3, "c": 0},
        {"op": 'imp', "a": 23, "b": 5, "c": 0},
    ],
    'pre-u5-how-many-hundredths': [
        {"op": 'hun', "a": 1, "b": 9, "c": 0},
        {"op": 'hun', "a": 3, "b": 5, "c": 0},
        {"op": 'hun', "a": 5, "b": 1, "c": 0},
        {"op": 'hun', "a": 6, "b": 6, "c": 0},
        {"op": 'hun', "a": 8, "b": 1, "c": 0},
    ],
    'pre-u5-times-by-ten': [
        {"op": 'x10', "a": 2, "b": 1, "c": 0},
        {"op": 'x10', "a": 3, "b": 7, "c": 0},
        {"op": 'x10', "a": 5, "b": 4, "c": 0},
        {"op": 'x10', "a": 6, "b": 7, "c": 0},
        {"op": 'x10', "a": 8, "b": 5, "c": 0},
    ],
    'pre-u5-tenths-times-a-number': [
        {"op": 'dth', "a": 2, "b": 4, "c": 0},
        {"op": 'dth', "a": 2, "b": 9, "c": 0},
        {"op": 'dth', "a": 3, "b": 9, "c": 0},
        {"op": 'dth', "a": 6, "b": 6, "c": 0},
        {"op": 'dth', "a": 7, "b": 7, "c": 0},
    ],
    'pre-u5-sharing-a-decimal': [
        {"op": 'dsh', "a": 1, "b": 2, "c": 4},
        {"op": 'dsh', "a": 3, "b": 6, "c": 6},
        {"op": 'dsh', "a": 1, "b": 8, "c": 2},
        {"op": 'dsh', "a": 3, "b": 6, "c": 3},
        {"op": 'dsh', "a": 3, "b": 0, "c": 2},
    ],
    'pre-u6-keeping-a-ratio': [
        {"op": 'rat', "a": 3, "b": 2, "c": 6},
        {"op": 'rat', "a": 4, "b": 5, "c": 8},
        {"op": 'rat', "a": 6, "b": 7, "c": 12},
        {"op": 'rat', "a": 3, "b": 4, "c": 15},
        {"op": 'rat', "a": 4, "b": 6, "c": 16},
    ],
    'pre-u6-scaling-a-rate': [
        {"op": 'rte', "a": 2, "b": 2, "c": 8},
        {"op": 'rte', "a": 3, "b": 5, "c": 20},
        {"op": 'rte', "a": 2, "b": 4, "c": 36},
        {"op": 'rte', "a": 4, "b": 7, "c": 42},
        {"op": 'rte', "a": 2, "b": 2, "c": 34},
    ],
    'pre-u6-filling-in-a-proportion': [
        {"op": 'prop', "a": 2, "b": 5, "c": 10},
        {"op": 'prop', "a": 2, "b": 5, "c": 20},
        {"op": 'prop', "a": 5, "b": 4, "c": 8},
        {"op": 'prop', "a": 6, "b": 9, "c": 21},
        {"op": 'prop', "a": 4, "b": 5, "c": 25},
    ],
    'pre-u6-sharing-in-a-ratio': [
        {"op": 'shr', "a": 2, "b": 4, "c": 12},
        {"op": 'shr', "a": 2, "b": 3, "c": 25},
        {"op": 'shr', "a": 6, "b": 5, "c": 22},
        {"op": 'shr', "a": 2, "b": 3, "c": 45},
        {"op": 'shr', "a": 3, "b": 2, "c": 40},
    ],
    'pre-u7-any-percent': [
        {"op": 'pcn', "a": 40, "b": 10, "c": 0},
        {"op": 'pcn', "a": 20, "b": 60, "c": 0},
        {"op": 'pcn', "a": 60, "b": 30, "c": 0},
        {"op": 'pcn', "a": 90, "b": 30, "c": 0},
        {"op": 'pcn', "a": 60, "b": 70, "c": 0},
    ],
    'pre-u7-what-percent-is-that': [
        {"op": 'asp', "a": 2, "b": 20, "c": 0},
        {"op": 'asp', "a": 8, "b": 40, "c": 0},
        {"op": 'asp', "a": 12, "b": 40, "c": 0},
        {"op": 'asp', "a": 13, "b": 25, "c": 0},
        {"op": 'asp', "a": 6, "b": 8, "c": 0},
    ],
    'pre-u7-finding-the-whole': [
        {"op": 'pwh', "a": 40, "b": 12, "c": 0},
        {"op": 'pwh', "a": 90, "b": 36, "c": 0},
        {"op": 'pwh', "a": 40, "b": 24, "c": 0},
        {"op": 'pwh', "a": 90, "b": 63, "c": 0},
        {"op": 'pwh', "a": 40, "b": 36, "c": 0},
    ],
    'pre-u7-a-price-goes-up': [
        {"op": 'pup', "a": 20, "b": 30, "c": 0},
        {"op": 'pup', "a": 30, "b": 30, "c": 1},
        {"op": 'pup', "a": 40, "b": 80, "c": 0},
        {"op": 'pup', "a": 20, "b": 50, "c": 1},
        {"op": 'pup', "a": 50, "b": 50, "c": 1},
    ],
    'pre-u8-changing-units': [
        {"op": 'cnv', "a": 3, "b": 10, "c": 0},
        {"op": 'cnv', "a": 4, "b": 10, "c": 0},
        {"op": 'cnv', "a": 9, "b": 10, "c": 0},
        {"op": 'cnv', "a": 1, "b": 100, "c": 0},
        {"op": 'cnv', "a": 5, "b": 100, "c": 0},
    ],
    'pre-u8-area-of-a-triangle': [
        {"op": 'tri', "a": 2, "b": 4, "c": 0},
        {"op": 'tri', "a": 5, "b": 4, "c": 0},
        {"op": 'tri', "a": 10, "b": 3, "c": 0},
        {"op": 'tri', "a": 8, "b": 6, "c": 0},
        {"op": 'tri', "a": 8, "b": 9, "c": 0},
    ],
    'pre-u8-angles-on-a-line': [
        {"op": 'sla', "a": 159, "b": 0, "c": 0},
        {"op": 'sla', "a": 132, "b": 0, "c": 0},
        {"op": 'sla', "a": 104, "b": 0, "c": 0},
        {"op": 'sla', "a": 76, "b": 0, "c": 0},
        {"op": 'sla', "a": 47, "b": 0, "c": 0},
    ],
    'pre-u8-angles-in-a-triangle': [
        {"op": 'tri3', "a": 14, "b": 90, "c": 0},
        {"op": 'tri3', "a": 13, "b": 80, "c": 0},
        {"op": 'tri3', "a": 10, "b": 73, "c": 0},
        {"op": 'tri3', "a": 10, "b": 65, "c": 0},
        {"op": 'tri3', "a": 10, "b": 57, "c": 0},
    ],
    'pre-u9-a-letter-holds-a-number': [
        {"op": 'evx', "a": 3, "b": 2, "c": 0},
        {"op": 'evx', "a": 2, "b": 7, "c": 0},
        {"op": 'evx', "a": 6, "b": 4, "c": 0},
        {"op": 'evx', "a": 7, "b": 5, "c": 0},
        {"op": 'evx', "a": 7, "b": 7, "c": 0},
    ],
    'pre-u9-a-number-against-a-letter': [
        {"op": 'mlx', "a": 3, "b": 2, "c": 0},
        {"op": 'mlx', "a": 2, "b": 6, "c": 0},
        {"op": 'mlx', "a": 7, "b": 2, "c": 0},
        {"op": 'mlx', "a": 4, "b": 6, "c": 0},
        {"op": 'mlx', "a": 5, "b": 6, "c": 0},
    ],
    'pre-u9-collecting-x': [
        {"op": 'clt', "a": 3, "b": 3, "c": 0},
        {"op": 'clt', "a": 2, "b": 7, "c": 0},
        {"op": 'clt', "a": 7, "b": 3, "c": 0},
        {"op": 'clt', "a": 5, "b": 7, "c": 0},
        {"op": 'clt', "a": 5, "b": 9, "c": 0},
    ],
    'pre-u9-the-times-reaches-both': [
        {"op": 'dst', "a": 3, "b": 2, "c": 0},
        {"op": 'dst', "a": 2, "b": 5, "c": 0},
        {"op": 'dst', "a": 4, "b": 3, "c": 0},
        {"op": 'dst', "a": 3, "b": 6, "c": 0},
        {"op": 'dst', "a": 4, "b": 6, "c": 0},
    ],
    'alg1-u1-two-steps-with-a-letter': [
        {"op": 'ev2', "a": 3, "b": 2, "c": 2},
        {"op": 'ev2', "a": 6, "b": 2, "c": 2},
        {"op": 'ev2', "a": 6, "b": 2, "c": 6},
        {"op": 'ev2', "a": 6, "b": 3, "c": 5},
        {"op": 'ev2', "a": 6, "b": 4, "c": 5},
    ],
    'alg1-u1-two-letters': [
        {"op": 'evxy', "a": 2, "b": 2, "c": 3},
        {"op": 'evxy', "a": 2, "b": 4, "c": 3},
        {"op": 'evxy', "a": 5, "b": 3, "c": 4},
        {"op": 'evxy', "a": 6, "b": 3, "c": 5},
        {"op": 'evxy', "a": 6, "b": 4, "c": 5},
    ],
    'alg1-u1-collecting-past-a-y': [
        {"op": 'cl2', "a": 2, "b": 2, "c": 3},
        {"op": 'cl2', "a": 5, "b": 5, "c": 4},
        {"op": 'cl2', "a": 3, "b": 2, "c": 8},
        {"op": 'cl2', "a": 6, "b": 4, "c": 6},
        {"op": 'cl2', "a": 6, "b": 5, "c": 8},
    ],
    'alg1-u1-minus-goes-through': [
        {"op": 'dstm', "a": 3, "b": 2, "c": 0},
        {"op": 'dstm', "a": 2, "b": 4, "c": 0},
        {"op": 'dstm', "a": 4, "b": 3, "c": 0},
        {"op": 'dstm', "a": 7, "b": 2, "c": 0},
        {"op": 'dstm', "a": 8, "b": 3, "c": 0},
    ],
    'alg1-u2-undoing-a-plus': [
        {"op": 'un1', "a": 2, "b": 4, "c": 0},
        {"op": 'un1', "a": 6, "b": 12, "c": 0},
        {"op": 'un1', "a": 3, "b": 12, "c": 0},
        {"op": 'un1', "a": 7, "b": 18, "c": 0},
        {"op": 'un1', "a": 3, "b": 17, "c": 0},
    ],
    'alg1-u2-undoing-a-times': [
        {"op": 'un2', "a": 5, "b": 10, "c": 0},
        {"op": 'un2', "a": 4, "b": 16, "c": 0},
        {"op": 'un2', "a": 6, "b": 30, "c": 0},
        {"op": 'un2', "a": 3, "b": 21, "c": 0},
        {"op": 'un2', "a": 5, "b": 40, "c": 0},
    ],
    'alg1-u2-two-steps-back': [
        {"op": 'un3', "a": 2, "b": 2, "c": 6},
        {"op": 'un3', "a": 2, "b": 4, "c": 12},
        {"op": 'un3', "a": 2, "b": 7, "c": 19},
        {"op": 'un3', "a": 3, "b": 6, "c": 30},
        {"op": 'un3', "a": 4, "b": 5, "c": 45},
    ],
    'alg1-u2-the-biggest-x': [
        {"op": 'ineq', "a": 3, "b": 7, "c": 0},
        {"op": 'ineq', "a": 4, "b": 11, "c": 0},
        {"op": 'ineq', "a": 2, "b": 11, "c": 0},
        {"op": 'ineq', "a": 6, "b": 16, "c": 0},
        {"op": 'ineq', "a": 3, "b": 15, "c": 0},
    ],
    'alg1-u3-the-number-machine': [
        {"op": 'fm1', "a": 3, "b": 2, "c": 2},
        {"op": 'fm1', "a": 2, "b": 3, "c": 4},
        {"op": 'fm1', "a": 2, "b": 4, "c": 5},
        {"op": 'fm1', "a": 5, "b": 2, "c": 3},
        {"op": 'fm1', "a": 4, "b": 4, "c": 4},
    ],
    'alg1-u3-f-of-x': [
        {"op": 'fnot', "a": 3, "b": 2, "c": 0},
        {"op": 'fnot', "a": 2, "b": 7, "c": 0},
        {"op": 'fnot', "a": 5, "b": 5, "c": 0},
        {"op": 'fnot', "a": 6, "b": 6, "c": 0},
        {"op": 'fnot', "a": 5, "b": 9, "c": 0},
    ],
    'alg1-u3-two-machines': [
        {"op": 'fm2', "a": 3, "b": 2, "c": 3},
        {"op": 'fm2', "a": 4, "b": 2, "c": 4},
        {"op": 'fm2', "a": 5, "b": 2, "c": 4},
        {"op": 'fm2', "a": 3, "b": 3, "c": 4},
        {"op": 'fm2', "a": 2, "b": 5, "c": 3},
    ],
    'alg1-u3-which-input': [
        {"op": 'fback', "a": 2, "b": 4, "c": 0},
        {"op": 'fback', "a": 7, "b": 12, "c": 0},
        {"op": 'fback', "a": 2, "b": 10, "c": 0},
        {"op": 'fback', "a": 5, "b": 15, "c": 0},
        {"op": 'fback', "a": 5, "b": 17, "c": 0},
    ],
    'alg1-u4-reading-the-line': [
        {"op": 'lny', "a": 3, "b": 2, "c": 0},
        {"op": 'lny', "a": 6, "b": 3, "c": 0},
        {"op": 'lny', "a": 7, "b": 4, "c": 0},
        {"op": 'lny', "a": 6, "b": 7, "c": 0},
        {"op": 'lny', "a": 7, "b": 8, "c": 0},
    ],
    'alg1-u4-the-climb': [
        {"op": 'slp', "a": 2, "b": 1, "c": 4},
        {"op": 'slp', "a": 3, "b": 4, "c": 4},
        {"op": 'slp', "a": 4, "b": 4, "c": 9},
        {"op": 'slp', "a": 6, "b": 2, "c": 4},
        {"op": 'slp', "a": 7, "b": 4, "c": 6},
    ],
    'alg1-u4-where-it-starts': [
        {"op": 'yint', "a": 4, "b": 2, "c": 0},
        {"op": 'yint', "a": 7, "b": 4, "c": 0},
        {"op": 'yint', "a": 9, "b": 5, "c": 0},
        {"op": 'yint', "a": 3, "b": 7, "c": 0},
        {"op": 'yint', "a": 5, "b": 8, "c": 0},
    ],
    'alg1-u4-start-and-climb': [
        {"op": 'lin2', "a": 2, "b": 1, "c": 3},
        {"op": 'lin2', "a": 2, "b": 2, "c": 4},
        {"op": 'lin2', "a": 2, "b": 2, "c": 5},
        {"op": 'lin2', "a": 3, "b": 3, "c": 4},
        {"op": 'lin2', "a": 4, "b": 2, "c": 4},
    ],
    'alg1-u5-where-two-rules-agree': [
        {"op": 'sys1', "a": 14, "b": 3},
        {"op": 'sys1', "a": 12, "b": 3},
        {"op": 'sys1', "a": 10, "b": 3},
        {"op": 'sys1', "a": 12, "b": 4},
        {"op": 'sys1', "a": 8, "b": 3},
    ],
    'alg1-u5-swapping-in': [
        {"op": 'sys2', "a": 4, "b": 10, "c": 0},
        {"op": 'sys2', "a": 2, "b": 12, "c": 0},
        {"op": 'sys2', "a": 2, "b": 14, "c": 0},
        {"op": 'sys2', "a": 2, "b": 16, "c": 0},
        {"op": 'sys2', "a": 2, "b": 18, "c": 0},
    ],
    'alg1-u5-sum-and-difference': [
        {"op": 'sumd', "a": 6, "b": 4, "c": 0},
        {"op": 'sumd', "a": 14, "b": 4, "c": 0},
        {"op": 'sumd', "a": 16, "b": 6, "c": 0},
        {"op": 'sumd', "a": 16, "b": 10, "c": 0},
        {"op": 'sumd', "a": 24, "b": 6, "c": 0},
    ],
    'alg1-u5-the-eraser-vanishes': [
        {"op": 'elim', "a": 14, "b": 11, "c": 0},
        {"op": 'elim', "a": 14, "b": 10, "c": 0},
        {"op": 'elim', "a": 14, "b": 9, "c": 0},
        {"op": 'elim', "a": 16, "b": 9, "c": 0},
        {"op": 'elim', "a": 20, "b": 12, "c": 0},
    ],
    'alg1-u6-counting-the-copies': [
        {"op": 'exadd', "a": 4, "b": 2, "c": 0},
        {"op": 'exadd', "a": 4, "b": 3, "c": 0},
        {"op": 'exadd', "a": 5, "b": 2, "c": 0},
        {"op": 'exadd', "a": 5, "b": 3, "c": 0},
        {"op": 'exadd', "a": 3, "b": 6, "c": 0},
    ],
    'alg1-u6-copies-of-copies': [
        {"op": 'exmul', "a": 3, "b": 2, "c": 0},
        {"op": 'exmul', "a": 4, "b": 2, "c": 0},
        {"op": 'exmul', "a": 2, "b": 5, "c": 0},
        {"op": 'exmul', "a": 2, "b": 6, "c": 0},
        {"op": 'exmul', "a": 3, "b": 5, "c": 0},
    ],
    'alg1-u6-times-ten-again': [
        {"op": 'sci', "a": 2, "b": 6, "c": 0},
        {"op": 'sci', "a": 2, "b": 8, "c": 0},
        {"op": 'sci', "a": 3, "b": 3, "c": 0},
        {"op": 'sci', "a": 3, "b": 7, "c": 0},
        {"op": 'sci', "a": 3, "b": 9},
    ],
    'alg1-u6-the-doubling-pond': [
        {"op": 'dbl', "a": 3, "b": 3, "c": 0},
        {"op": 'dbl', "a": 5, "b": 3},
        {"op": 'dbl', "a": 4, "b": 5},
        {"op": 'dbl', "a": 4, "b": 4},
        {"op": 'dbl', "a": 5, "b": 2},
    ],
    'alg1-u7-the-four-rooms': [
        {"op": 'foil', "a": 4, "b": 2, "c": 0},
        {"op": 'foil', "a": 4, "b": 3, "c": 0},
        {"op": 'foil', "a": 5, "b": 3, "c": 0},
        {"op": 'foil', "a": 3, "b": 6, "c": 0},
        {"op": 'foil', "a": 5, "b": 5, "c": 0},
    ],
    'alg1-u7-factoring-backwards': [
        {"op": 'fnum', "a": 5, "b": 2, "c": 0},
        {"op": 'fnum', "a": 4, "b": 4, "c": 0},
        {"op": 'fnum', "a": 6, "b": 4, "c": 0},
        {"op": 'fnum', "a": 6, "b": 5, "c": 0},
        {"op": 'fnum', "a": 3, "b": 6, "c": 0},
    ],
    'alg1-u7-the-common-factor': [
        {"op": 'gcfx', "a": 2, "b": 5, "c": 2},
        {"op": 'gcfx', "a": 5, "b": 3, "c": 2},
        {"op": 'gcfx', "a": 7, "b": 5, "c": 2},
        {"op": 'gcfx', "a": 5, "b": 2, "c": 4},
        {"op": 'gcfx', "a": 5, "b": 4, "c": 5},
    ],
    'alg1-u7-the-vanishing-middle': [
        {"op": 'dsq', "a": 12, "b": 0},
        {"op": 'dsq', "a": 11, "b": 0},
        {"op": 'dsq', "a": 9, "b": 0},
        {"op": 'dsq', "a": 8, "b": 0},
        {"op": 'dsq', "a": 7, "b": 0},
    ],
    'alg1-u8-the-curve': [
        {"op": 'sqy', "a": 3, "b": 2, "c": 0},
        {"op": 'sqy', "a": 4, "b": 3, "c": 0},
        {"op": 'sqy', "a": 5, "b": 4, "c": 0},
        {"op": 'sqy', "a": 6, "b": 4, "c": 0},
        {"op": 'sqy', "a": 7, "b": 6, "c": 0},
    ],
    'alg1-u8-two-answers': [
        {"op": 'roots', "a": 5, "b": 2, "c": 0},
        {"op": 'roots', "a": 2, "b": 4, "c": 0},
        {"op": 'roots', "a": 2, "b": 6, "c": 0},
        {"op": 'roots', "a": 5, "b": 7, "c": 0},
        {"op": 'roots', "a": 7, "b": 8, "c": 0},
    ],
    'alg1-u8-the-lowest-point': [
        {"op": 'vtx', "a": 3, "b": 2, "c": 0},
        {"op": 'vtx', "a": 8, "b": 4, "c": 0},
        {"op": 'vtx', "a": 9, "b": 5, "c": 0},
        {"op": 'vtx', "a": 3, "b": 7, "c": 0},
        {"op": 'vtx', "a": 5, "b": 8, "c": 0},
    ],
    'alg1-u8-the-ball-comes-down': [
        {"op": 'hitg', "a": 12, "b": 0},
        {"op": 'hitg', "a": 11, "b": 0},
        {"op": 'hitg', "a": 10, "b": 0},
        {"op": 'hitg', "a": 9, "b": 0},
        {"op": 'hitg', "a": 8, "b": 0},
    ],
    'alg1-u9-the-mean': [
        {"op": 'mean', "a": 4, "b": 2, "c": 0},
        {"op": 'mean', "a": 8, "b": 3, "c": 0},
        {"op": 'mean', "a": 3, "b": 6, "c": 0},
        {"op": 'mean', "a": 6, "b": 8, "c": 0},
        {"op": 'mean', "a": 6, "b": 11, "c": 0},
    ],
    'alg1-u9-the-median': [
        {"op": 'medn', "a": 2, "b": 6, "c": 0},
        {"op": 'medn', "a": 2, "b": 10, "c": 0},
        {"op": 'medn', "a": 3, "b": 12, "c": 0},
        {"op": 'medn', "a": 4, "b": 14, "c": 0},
        {"op": 'medn', "a": 4, "b": 16, "c": 0},
    ],
    'alg1-u9-the-range': [
        {"op": 'rnge', "a": 2, "b": 6, "c": 0},
        {"op": 'rnge', "a": 6, "b": 19, "c": 0},
        {"op": 'rnge', "a": 4, "b": 22, "c": 0},
        {"op": 'rnge', "a": 2, "b": 25, "c": 0},
        {"op": 'rnge', "a": 7, "b": 34, "c": 0},
    ],
    'alg1-u9-the-odd-one-out': [
        {"op": 'outl', "a": 1, "b": 2, "c": 17},
        {"op": 'outl', "a": 3, "b": 3, "c": 23},
        {"op": 'outl', "a": 1, "b": 5, "c": 25},
        {"op": 'outl', "a": 3, "b": 6, "c": 21},
        {"op": 'outl', "a": 2, "b": 8, "c": 23},
    ],
    'geo-u1-two-make-a-corner': [
        {"op": 'comp', "a": 79, "b": 0, "c": 0},
        {"op": 'comp', "a": 67, "b": 0, "c": 0},
        {"op": 'comp', "a": 52, "b": 0, "c": 0},
        {"op": 'comp', "a": 38, "b": 0, "c": 0},
        {"op": 'comp', "a": 23, "b": 0, "c": 0},
    ],
    'geo-u1-when-lines-cross': [
        {"op": 'vert', "a": 69, "b": 0, "c": 0},
        {"op": 'vert', "a": 60, "b": 0, "c": 0},
        {"op": 'vert', "a": 50, "b": 0, "c": 0},
        {"op": 'vert', "a": 41, "b": 0, "c": 0},
        {"op": 'vert', "a": 31, "b": 0, "c": 0},
    ],
    'geo-u1-across-the-circle': [
        {"op": 'circ', "a": 18, "b": 0, "c": 0},
        {"op": 'circ', "a": 24, "b": 0, "c": 0},
        {"op": 'circ', "a": 28, "b": 0, "c": 0},
        {"op": 'circ', "a": 34, "b": 0, "c": 0},
        {"op": 'circ', "a": 36, "b": 0, "c": 0},
    ],
    'geo-u1-halfway-along': [
        {"op": 'mid', "a": 2, "b": 10, "c": 0},
        {"op": 'mid', "a": 6, "b": 20, "c": 0},
        {"op": 'mid', "a": 8, "b": 26, "c": 0},
        {"op": 'mid', "a": 4, "b": 36, "c": 0},
        {"op": 'mid', "a": 12, "b": 32, "c": 0},
    ],
    'geo-u2-slide-it-over': [
        {"op": 'tran', "a": 3, "b": 1, "c": 2},
        {"op": 'tran', "a": 5, "b": 2, "c": 3},
        {"op": 'tran', "a": 7, "b": 5, "c": 2},
        {"op": 'tran', "a": 8, "b": 6, "c": 2},
        {"op": 'tran', "a": 9, "b": 7, "c": 2},
    ],
    'geo-u2-flip-it-across': [
        {"op": 'refl', "a": 9, "b": 6},
        {"op": 'refl', "a": 8, "b": 5},
        {"op": 'refl', "a": 7, "b": 9},
        {"op": 'refl', "a": 7, "b": 2},
        {"op": 'refl', "a": 6, "b": 4},
    ],
    'geo-u2-half-turn': [
        {"op": 'htrn', "a": 5, "b": 9},
        {"op": 'htrn', "a": 3, "b": 8},
        {"op": 'htrn', "a": 2, "b": 7},
        {"op": 'htrn', "a": 9, "b": 7},
        {"op": 'htrn', "a": 4, "b": 6},
    ],
    'geo-u2-turns-onto-itself': [
        {"op": 'rota', "a": 24, "b": 0},
        {"op": 'rota', "a": 20, "b": 0},
        {"op": 'rota', "a": 18, "b": 0},
        {"op": 'rota', "a": 15, "b": 0},
        {"op": 'rota', "a": 10, "b": 0},
    ],
    'geo-u3-matching-parts': [
        {"op": 'cong', "a": 2, "b": 4, "c": 3},
        {"op": 'cong', "a": 9, "b": 10, "c": 5},
        {"op": 'cong', "a": 8, "b": 14, "c": 7},
        {"op": 'cong', "a": 7, "b": 8, "c": 9},
        {"op": 'cong', "a": 7, "b": 9, "c": 11},
    ],
    'geo-u3-two-equal-sides': [
        {"op": 'isos', "a": 21, "b": 0, "c": 0},
        {"op": 'isos', "a": 31, "b": 0, "c": 0},
        {"op": 'isos', "a": 42, "b": 0, "c": 0},
        {"op": 'isos', "a": 52, "b": 0, "c": 0},
        {"op": 'isos', "a": 63, "b": 0, "c": 0},
    ],
    'geo-u3-the-outside-angle': [
        {"op": 'extr', "a": 20, "b": 45, "c": 0},
        {"op": 'extr', "a": 24, "b": 46, "c": 0},
        {"op": 'extr', "a": 22, "b": 53, "c": 0},
        {"op": 'extr', "a": 20, "b": 60, "c": 0},
        {"op": 'extr', "a": 28, "b": 56, "c": 0},
    ],
    'geo-u3-share-the-rest': [
        {"op": 'chas', "a": 26, "b": 0, "c": 0},
        {"op": 'chas', "a": 36, "b": 0, "c": 0},
        {"op": 'chas', "a": 48, "b": 0, "c": 0},
        {"op": 'chas', "a": 58, "b": 0, "c": 0},
        {"op": 'chas', "a": 72, "b": 0, "c": 0},
    ],
    'geo-u4-the-enlarging-copy': [
        {"op": 'scal', "a": 4, "b": 4, "c": 0},
        {"op": 'scal', "a": 14, "b": 2, "c": 0},
        {"op": 'scal', "a": 16, "b": 2, "c": 0},
        {"op": 'scal', "a": 16, "b": 4},
        {"op": 'scal', "a": 12, "b": 4},
    ],
    'geo-u4-finding-the-factor': [
        {"op": 'sfac', "a": 2, "b": 6, "c": 0},
        {"op": 'sfac', "a": 3, "b": 9, "c": 0},
        {"op": 'sfac', "a": 4, "b": 12, "c": 0},
        {"op": 'sfac', "a": 3, "b": 15, "c": 0},
        {"op": 'sfac', "a": 4, "b": 20, "c": 0},
    ],
    'geo-u4-the-matching-side': [
        {"op": 'mside', "a": 2, "b": 4, "c": 2},
        {"op": 'mside', "a": 3, "b": 7, "c": 2},
        {"op": 'mside', "a": 2, "b": 6, "c": 3},
        {"op": 'mside', "a": 4, "b": 7, "c": 3},
        {"op": 'mside', "a": 2, "b": 9, "c": 3},
    ],
    'geo-u4-the-area-surprise': [
        {"op": 'sare', "a": 2, "b": 3, "c": 0},
        {"op": 'sare', "a": 5, "b": 2, "c": 0},
        {"op": 'sare', "a": 2, "b": 4, "c": 0},
        {"op": 'sare', "a": 9, "b": 2, "c": 0},
        {"op": 'sare', "a": 7, "b": 3, "c": 0},
    ],
    'geo-u5-the-longest-side': [
        {"op": 'pyth', "a": 4, "b": 3, "c": 5},
        {"op": 'pyth', "a": 8, "b": 6, "c": 10},
        {"op": 'pyth', "a": 5, "b": 12, "c": 13},
        {"op": 'pyth', "a": 9, "b": 12, "c": 15},
        {"op": 'pyth', "a": 24, "b": 32, "c": 40},
    ],
    'geo-u5-the-missing-leg': [
        {"op": 'leg', "a": 3, "b": 4, "c": 5},
        {"op": 'leg', "a": 8, "b": 6, "c": 10},
        {"op": 'leg', "a": 5, "b": 12, "c": 13},
        {"op": 'leg', "a": 12, "b": 9, "c": 15},
        {"op": 'leg', "a": 7, "b": 24, "c": 25},
    ],
    'geo-u5-the-climb-ratio': [
        {"op": 'tang', "a": 4, "b": 8, "c": 0},
        {"op": 'tang', "a": 6, "b": 18},
        {"op": 'tang', "a": 4, "b": 16},
        {"op": 'tang', "a": 5, "b": 15},
        {"op": 'tang', "a": 3, "b": 12},
    ],
    'geo-u5-using-the-tangent': [
        {"op": 'topp', "a": 3, "b": 3, "c": 0},
        {"op": 'topp', "a": 8, "b": 2, "c": 0},
        {"op": 'topp', "a": 9, "b": 2, "c": 0},
        {"op": 'topp', "a": 9, "b": 3},
        {"op": 'topp', "a": 8, "b": 3},
    ],
    'geo-u6-the-rest-of-the-circle': [
        {"op": 'cent', "a": 21, "b": 0, "c": 0},
        {"op": 'cent', "a": 47, "b": 0, "c": 0},
        {"op": 'cent', "a": 74, "b": 0, "c": 0},
        {"op": 'cent', "a": 98, "b": 0, "c": 0},
        {"op": 'cent', "a": 124, "b": 0, "c": 0},
    ],
    'geo-u6-half-the-arc': [
        {"op": 'insc', "a": 32, "b": 0, "c": 0},
        {"op": 'insc', "a": 58, "b": 0, "c": 0},
        {"op": 'insc', "a": 86, "b": 0, "c": 0},
        {"op": 'insc', "a": 110, "b": 0, "c": 0},
        {"op": 'insc', "a": 134, "b": 0, "c": 0},
    ],
    'geo-u6-double-it-back': [
        {"op": 'iarc', "a": 18, "b": 0, "c": 0},
        {"op": 'iarc', "a": 32, "b": 0, "c": 0},
        {"op": 'iarc', "a": 46, "b": 0, "c": 0},
        {"op": 'iarc', "a": 56, "b": 0, "c": 0},
        {"op": 'iarc', "a": 68, "b": 0, "c": 0},
    ],
    'geo-u6-a-piece-of-the-rim': [
        {"op": 'alen', "a": 30, "b": 24, "c": 0},
        {"op": 'alen', "a": 60, "b": 18, "c": 0},
        {"op": 'alen', "a": 30, "b": 72, "c": 0},
        {"op": 'alen', "a": 90, "b": 28, "c": 0},
        {"op": 'alen', "a": 60, "b": 60, "c": 0},
    ],
    'geo-u7-straight-up': [
        {"op": 'vseg', "a": 1, "b": 2, "c": 4},
        {"op": 'vseg', "a": 1, "b": 4, "c": 7},
        {"op": 'vseg', "a": 8, "b": 3, "c": 6},
        {"op": 'vseg', "a": 6, "b": 5, "c": 9},
        {"op": 'vseg', "a": 7, "b": 3, "c": 8},
    ],
    'geo-u7-the-straight-path': [
        {"op": 'dist', "a": 1, "b": 1, "c": 1},
        {"op": 'dist', "a": 3, "b": 6, "c": 1},
        {"op": 'dist', "a": 6, "b": 5, "c": 1},
        {"op": 'dist', "a": 1, "b": 2, "c": 2},
        {"op": 'dist', "a": 4, "b": 4, "c": 2},
    ],
    'geo-u7-the-middle-of-a-line': [
        {"op": 'mid2', "a": 1, "b": 3, "c": 5},
        {"op": 'mid2', "a": 3, "b": 5, "c": 7},
        {"op": 'mid2', "a": 2, "b": 8, "c": 10},
        {"op": 'mid2', "a": 3, "b": 9, "c": 11},
        {"op": 'mid2', "a": 6, "b": 9, "c": 8},
    ],
    'geo-u7-the-fourth-corner': [
        {"op": 'corn', "a": 1, "b": 2, "c": 4},
        {"op": 'corn', "a": 4, "b": 2, "c": 7},
        {"op": 'corn', "a": 6, "b": 4, "c": 8},
        {"op": 'corn', "a": 3, "b": 1, "c": 10},
        {"op": 'corn', "a": 5, "b": 3, "c": 11},
    ],
    'geo-u8-the-true-height': [
        {"op": 'para', "a": 3, "b": 4, "c": 5},
        {"op": 'para', "a": 8, "b": 2, "c": 3},
        {"op": 'para', "a": 6, "b": 4, "c": 5},
        {"op": 'para', "a": 6, "b": 5, "c": 6},
        {"op": 'para', "a": 9, "b": 4, "c": 6},
    ],
    'geo-u8-two-rooms': [
        {"op": 'lshp', "a": 3, "b": 2, "c": 3},
        {"op": 'lshp', "a": 3, "b": 3, "c": 4},
        {"op": 'lshp', "a": 5, "b": 3, "c": 4},
        {"op": 'lshp', "a": 5, "b": 4, "c": 3},
        {"op": 'lshp', "a": 5, "b": 5, "c": 3},
    ],
    'geo-u8-six-faces': [
        {"op": 'surf', "a": 7, "b": 0, "c": 0},
        {"op": 'surf', "a": 11, "b": 0, "c": 0},
        {"op": 'surf', "a": 14, "b": 0, "c": 0},
        {"op": 'surf', "a": 19, "b": 0, "c": 0},
        {"op": 'surf', "a": 22, "b": 0, "c": 0},
    ],
    'geo-u8-the-volume-surprise': [
        {"op": 'svol', "a": 9, "b": 2, "c": 0},
        {"op": 'svol', "a": 4, "b": 3},
        {"op": 'svol', "a": 3, "b": 3},
        {"op": 'svol', "a": 10, "b": 2},
        {"op": 'svol', "a": 8, "b": 2},
    ],
    'geo-u9-out-of-all': [
        {"op": 'poft', "a": 3, "b": 2, "c": 0},
        {"op": 'poft', "a": 4, "b": 5, "c": 0},
        {"op": 'poft', "a": 5, "b": 6, "c": 0},
        {"op": 'poft', "a": 8, "b": 4, "c": 0},
        {"op": 'poft', "a": 8, "b": 6, "c": 0},
    ],
    'geo-u9-the-other-chance': [
        {"op": 'notp', "a": 3, "b": 7, "c": 0},
        {"op": 'notp', "a": 5, "b": 11, "c": 0},
        {"op": 'notp', "a": 6, "b": 14, "c": 0},
        {"op": 'notp', "a": 4, "b": 14, "c": 0},
        {"op": 'notp', "a": 4, "b": 16, "c": 0},
    ],
    'geo-u9-how-many-ways': [
        {"op": 'outc', "a": 2, "b": 3, "c": 0},
        {"op": 'outc', "a": 2, "b": 4, "c": 0},
        {"op": 'outc', "a": 3, "b": 4, "c": 0},
        {"op": 'outc', "a": 8, "b": 2, "c": 0},
        {"op": 'outc', "a": 7, "b": 3, "c": 0},
    ],
    'geo-u9-reading-the-table': [
        {"op": 'twop', "a": 2, "b": 3, "c": 2},
        {"op": 'twop', "a": 5, "b": 5, "c": 4},
        {"op": 'twop', "a": 5, "b": 5, "c": 6},
        {"op": 'twop', "a": 5, "b": 7, "c": 8},
        {"op": 'twop', "a": 5, "b": 9, "c": 10},
    ],
    'alg2-u1-how-far-from-zero': [
        {"op": 'absv', "a": 2, "b": 4, "c": 0},
        {"op": 'absv', "a": 4, "b": 9, "c": 0},
        {"op": 'absv', "a": 3, "b": 10, "c": 0},
        {"op": 'absv', "a": 2, "b": 11, "c": 0},
        {"op": 'absv', "a": 9, "b": 19, "c": 0},
    ],
    'alg2-u1-inside-the-distance': [
        {"op": 'absc', "a": 5, "b": 0, "c": 0},
        {"op": 'absc', "a": 15, "b": 0},
        {"op": 'absc', "a": 14, "b": 0},
        {"op": 'absc', "a": 12, "b": 0},
        {"op": 'absc', "a": 11, "b": 0},
    ],
    'alg2-u1-the-bananas-cancel': [
        {"op": 'el2', "a": 8, "b": 4, "c": 0},
        {"op": 'el2', "a": 13, "b": 5, "c": 0},
        {"op": 'el2', "a": 20, "b": 12, "c": 0},
        {"op": 'el2', "a": 19, "b": 7, "c": 0},
        {"op": 'el2', "a": 23, "b": 9, "c": 0},
    ],
    'alg2-u1-three-friends': [
        {"op": 'sys3', "a": 2, "b": 11, "c": 11},
        {"op": 'sys3', "a": 5, "b": 11, "c": 14},
        {"op": 'sys3', "a": 6, "b": 13, "c": 17},
        {"op": 'sys3', "a": 7, "b": 15, "c": 20},
        {"op": 'sys3', "a": 7, "b": 21, "c": 20},
    ],
    'alg2-u2-where-it-turns': [
        {"op": 'vtx2', "a": 2, "b": 1, "c": 0},
        {"op": 'vtx2', "a": 5, "b": 3, "c": 0},
        {"op": 'vtx2', "a": 7, "b": 2, "c": 0},
        {"op": 'vtx2', "a": 9, "b": 2, "c": 0},
        {"op": 'vtx2', "a": 11, "b": 2, "c": 0},
    ],
    'alg2-u2-both-answers-count': [
        {"op": 'rsum', "a": 3, "b": 2, "c": 0},
        {"op": 'rsum', "a": 5, "b": 2, "c": 0},
        {"op": 'rsum', "a": 5, "b": 4, "c": 0},
        {"op": 'rsum', "a": 7, "b": 3, "c": 0},
        {"op": 'rsum', "a": 7, "b": 4, "c": 0},
    ],
    'alg2-u2-the-test-number': [
        {"op": 'disc', "a": 8, "b": 17},
        {"op": 'disc', "a": 7, "b": 10},
        {"op": 'disc', "a": 6, "b": 9},
        {"op": 'disc', "a": 5, "b": 7},
        {"op": 'disc', "a": 5, "b": 4},
    ],
    'alg2-u2-a-new-number': [
        {"op": 'imag', "a": 225, "b": 0},
        {"op": 'imag', "a": 196, "b": 0},
        {"op": 'imag', "a": 169, "b": 0},
        {"op": 'imag', "a": 144, "b": 0},
        {"op": 'imag', "a": 121, "b": 0},
    ],
    'alg2-u3-degrees-add': [
        {"op": 'pdeg', "a": 2, "b": 4, "c": 0},
        {"op": 'pdeg', "a": 2, "b": 6, "c": 0},
        {"op": 'pdeg', "a": 7, "b": 2, "c": 0},
        {"op": 'pdeg', "a": 7, "b": 3, "c": 0},
        {"op": 'pdeg', "a": 4, "b": 8, "c": 0},
    ],
    'alg2-u3-the-wiggle-count': [
        {"op": 'turnc', "a": 4, "b": 0, "c": 0},
        {"op": 'turnc', "a": 6, "b": 0, "c": 0},
        {"op": 'turnc', "a": 15, "b": 0},
        {"op": 'turnc', "a": 14, "b": 0},
        {"op": 'turnc', "a": 13, "b": 0},
    ],
    'alg2-u3-three-crossings': [
        {"op": 'rsum3', "a": 1, "b": 2, "c": 5},
        {"op": 'rsum3', "a": 1, "b": 4, "c": 5},
        {"op": 'rsum3', "a": 2, "b": 4, "c": 5},
        {"op": 'rsum3', "a": 2, "b": 3, "c": 7},
        {"op": 'rsum3', "a": 2, "b": 5, "c": 6},
    ],
    'alg2-u3-feed-the-cube': [
        {"op": 'pval', "a": 2, "b": 1, "c": 2},
        {"op": 'pval', "a": 3, "b": 7, "c": 2},
        {"op": 'pval', "a": 3, "b": 3, "c": 3},
        {"op": 'pval', "a": 1, "b": 1, "c": 3},
        {"op": 'pval', "a": 1, "b": 6, "c": 3},
    ],
    'alg2-u4-sharing-shrinks': [
        {"op": 'rdiv', "a": 6, "b": 3, "c": 0},
        {"op": 'rdiv', "a": 12, "b": 6, "c": 0},
        {"op": 'rdiv', "a": 15, "b": 3, "c": 0},
        {"op": 'rdiv', "a": 20, "b": 5, "c": 0},
        {"op": 'rdiv', "a": 25, "b": 5, "c": 0},
    ],
    'alg2-u4-which-x-was-fed': [
        {"op": 'rsol', "a": 6, "b": 3, "c": 0},
        {"op": 'rsol', "a": 12, "b": 3, "c": 0},
        {"op": 'rsol', "a": 16, "b": 2, "c": 0},
        {"op": 'rsol', "a": 20, "b": 4, "c": 0},
        {"op": 'rsol', "a": 27, "b": 9, "c": 0},
    ],
    'alg2-u4-the-forbidden-x': [
        {"op": 'excl', "a": 2, "b": 1, "c": 0},
        {"op": 'excl', "a": 4, "b": 4, "c": 0},
        {"op": 'excl', "a": 6, "b": 5, "c": 0},
        {"op": 'excl', "a": 8, "b": 7, "c": 0},
        {"op": 'excl', "a": 10, "b": 7, "c": 0},
    ],
    'alg2-u4-the-survivor': [
        {"op": 'rasy', "a": 2, "b": 1, "c": 0},
        {"op": 'rasy', "a": 4, "b": 1, "c": 0},
        {"op": 'rasy', "a": 5, "b": 6, "c": 0},
        {"op": 'rasy', "a": 6, "b": 9, "c": 0},
        {"op": 'rasy', "a": 8, "b": 6, "c": 0},
    ],
    'alg2-u5-under-one-roof': [
        {"op": 'rmul', "a": 2, "b": 32, "c": 0},
        {"op": 'rmul', "a": 3, "b": 48, "c": 0},
        {"op": 'rmul', "a": 8, "b": 32, "c": 0},
        {"op": 'rmul', "a": 7, "b": 28},
        {"op": 'rmul', "a": 8, "b": 18},
    ],
    'alg2-u5-the-fraction-power': [
        {"op": 'rpow', "a": 100, "b": 0, "c": 0},
        {"op": 'rpow', "a": 576, "b": 0},
        {"op": 'rpow', "a": 484, "b": 0},
        {"op": 'rpow', "a": 400, "b": 0},
        {"op": 'rpow', "a": 324, "b": 0},
    ],
    'alg2-u5-undo-the-root': [
        {"op": 'rsq', "a": 13, "b": 0},
        {"op": 'rsq', "a": 12, "b": 0},
        {"op": 'rsq', "a": 11, "b": 0},
        {"op": 'rsq', "a": 10, "b": 0},
        {"op": 'rsq', "a": 9, "b": 0},
    ],
    'alg2-u5-between-the-squares': [
        {"op": 'rbet', "a": 17, "b": 0, "c": 0},
        {"op": 'rbet', "a": 46, "b": 0, "c": 0},
        {"op": 'rbet', "a": 67, "b": 0, "c": 0},
        {"op": 'rbet', "a": 90, "b": 0, "c": 0},
        {"op": 'rbet', "a": 110, "b": 0, "c": 0},
    ],
    'alg2-u6-the-fading-half': [
        {"op": 'hlfl', "a": 12, "b": 2, "c": 0},
        {"op": 'hlfl', "a": 32, "b": 4, "c": 0},
        {"op": 'hlfl', "a": 44, "b": 2, "c": 0},
        {"op": 'hlfl', "a": 56, "b": 3, "c": 0},
        {"op": 'hlfl', "a": 64, "b": 4, "c": 0},
    ],
    'alg2-u6-the-hidden-exponent': [
        {"op": 'logb', "a": 1024, "b": 2, "c": 10},
        {"op": 'logb', "a": 729, "b": 3, "c": 6},
        {"op": 'logb', "a": 512, "b": 2, "c": 9},
        {"op": 'logb', "a": 256, "b": 2, "c": 8},
        {"op": 'logb', "a": 243, "b": 3, "c": 5},
    ],
    'alg2-u6-logs-add': [
        {"op": 'logm', "a": 32, "b": 128},
        {"op": 'logm', "a": 32, "b": 64},
        {"op": 'logm', "a": 16, "b": 64},
        {"op": 'logm', "a": 8, "b": 64},
        {"op": 'logm', "a": 16, "b": 32},
    ],
    'alg2-u6-between-the-powers': [
        {"op": 'lbet', "a": 14, "b": 0, "c": 0},
        {"op": 'lbet', "a": 39, "b": 0, "c": 0},
        {"op": 'lbet', "a": 59, "b": 0, "c": 0},
        {"op": 'lbet', "a": 80, "b": 0, "c": 0},
        {"op": 'lbet', "a": 101, "b": 0, "c": 0},
    ],
    'alg2-u7-ride-the-pattern': [
        {"op": 'anth', "a": 3, "b": 2, "c": 5},
        {"op": 'anth', "a": 2, "b": 4, "c": 6},
        {"op": 'anth', "a": 5, "b": 3, "c": 8},
        {"op": 'anth', "a": 3, "b": 4, "c": 8},
        {"op": 'anth', "a": 3, "b": 5, "c": 8},
    ],
    'alg2-u7-times-again': [
        {"op": 'gnth', "a": 4, "b": 3, "c": 3},
        {"op": 'gnth', "a": 5, "b": 3, "c": 3},
        {"op": 'gnth', "a": 4, "b": 2, "c": 5},
        {"op": 'gnth', "a": 5, "b": 2, "c": 5},
        {"op": 'gnth', "a": 2, "b": 3, "c": 4},
    ],
    'alg2-u7-pair-the-ends': [
        {"op": 'gaus', "a": 10, "b": 0, "c": 0},
        {"op": 'gaus', "a": 32, "b": 0, "c": 0},
        {"op": 'gaus', "a": 49, "b": 0, "c": 0},
        {"op": 'gaus', "a": 66, "b": 0, "c": 0},
        {"op": 'gaus', "a": 83, "b": 0, "c": 0},
    ],
    'alg2-u7-walk-the-rule': [
        {"op": 'reca', "a": 5, "b": 3, "c": 0},
        {"op": 'reca', "a": 7, "b": 5, "c": 0},
        {"op": 'reca', "a": 6, "b": 2, "c": 0},
        {"op": 'reca', "a": 7, "b": 3, "c": 0},
        {"op": 'reca', "a": 9, "b": 5, "c": 0},
    ],
    'alg2-u8-the-height': [
        {"op": 'sinp', "a": 1170, "b": 0},
        {"op": 'sinp', "a": 1080, "b": 0},
        {"op": 'sinp', "a": 900, "b": 0},
        {"op": 'sinp', "a": 810, "b": 0},
        {"op": 'sinp', "a": 720, "b": 0},
    ],
    'alg2-u8-the-across': [
        {"op": 'cosp', "a": 1170, "b": 0},
        {"op": 'cosp', "a": 1080, "b": 0},
        {"op": 'cosp', "a": 900, "b": 0},
        {"op": 'cosp', "a": 810, "b": 0},
        {"op": 'cosp', "a": 630, "b": 0},
    ],
    'alg2-u8-spin-once-more': [
        {"op": 'spin', "a": 11, "b": 0, "c": 0},
        {"op": 'spin', "a": 24, "b": 0, "c": 0},
        {"op": 'spin', "a": 39, "b": 0, "c": 0},
        {"op": 'spin', "a": 53, "b": 0, "c": 0},
        {"op": 'spin', "a": 67, "b": 0, "c": 0},
    ],
    'alg2-u8-the-stretched-wave': [
        {"op": 'ampl', "a": 13, "b": 0, "c": 0},
        {"op": 'ampl', "a": 14, "b": 0, "c": 0},
        {"op": 'ampl', "a": 12, "b": 0},
        {"op": 'ampl', "a": 10, "b": 0},
        {"op": 'ampl', "a": 9, "b": 0},
    ],
    'alg2-u9-the-heavier-mean': [
        {"op": 'wavg', "a": 4, "b": 14, "c": 0},
        {"op": 'wavg', "a": 15, "b": 5, "c": 0},
        {"op": 'wavg', "a": 17, "b": 7, "c": 0},
        {"op": 'wavg', "a": 16, "b": 6},
        {"op": 'wavg', "a": 8, "b": 18},
    ],
    'alg2-u9-three-slots': [
        {"op": 'cnt3', "a": 2, "b": 3, "c": 2},
        {"op": 'cnt3', "a": 3, "b": 2, "c": 4},
        {"op": 'cnt3', "a": 4, "b": 2, "c": 4},
        {"op": 'cnt3', "a": 5, "b": 2, "c": 4},
        {"op": 'cnt3', "a": 5, "b": 2, "c": 5},
    ],
    'alg2-u9-what-to-expect': [
        {"op": 'expv', "a": 2, "b": 3, "c": 2},
        {"op": 'expv', "a": 4, "b": 7, "c": 2},
        {"op": 'expv', "a": 2, "b": 5, "c": 6},
        {"op": 'expv', "a": 3, "b": 9, "c": 5},
        {"op": 'expv', "a": 4, "b": 9, "c": 5},
    ],
    'alg2-u9-the-sample-speaks': [
        {"op": 'samp', "a": 4, "b": 3, "c": 2},
        {"op": 'samp', "a": 14, "b": 5, "c": 2},
        {"op": 'samp', "a": 4, "b": 3, "c": 5},
        {"op": 'samp', "a": 19, "b": 9, "c": 2},
        {"op": 'samp', "a": 16, "b": 5, "c": 5},
    ],
    'pc-u1-machines-in-a-row': [
        {"op": 'fcmp', "a": 2, "b": 3, "c": 2},
        {"op": 'fcmp', "a": 2, "b": 2, "c": 6},
        {"op": 'fcmp', "a": 6, "b": 2, "c": 5},
        {"op": 'fcmp', "a": 3, "b": 2, "c": 8},
        {"op": 'fcmp', "a": 7, "b": 2, "c": 7},
    ],
    'pc-u1-the-graph-slides': [
        {"op": 'fshf', "a": 2, "b": 3, "c": 1},
        {"op": 'fshf', "a": 3, "b": 5, "c": 4},
        {"op": 'fshf', "a": 3, "b": 7, "c": 5},
        {"op": 'fshf', "a": 5, "b": 6, "c": 5},
        {"op": 'fshf', "a": 5, "b": 8, "c": 5},
    ],
    'pc-u1-the-doorway': [
        {"op": 'fdom', "a": 13, "b": 0, "c": 0},
        {"op": 'fdom', "a": 12, "b": 0},
        {"op": 'fdom', "a": 10, "b": 0},
        {"op": 'fdom', "a": 9, "b": 0},
        {"op": 'fdom', "a": 8, "b": 0},
    ],
    'pc-u1-a-function-in-pieces': [
        {"op": 'fpie', "a": 4, "b": 2, "c": 3},
        {"op": 'fpie', "a": 7, "b": 3, "c": 3},
        {"op": 'fpie', "a": 5, "b": 3, "c": 5},
        {"op": 'fpie', "a": 7, "b": 3, "c": 6},
        {"op": 'fpie', "a": 7, "b": 3, "c": 7},
    ],
    'pc-u2-the-minus-parade': [
        {"op": 'negp', "a": 11, "b": 0},
        {"op": 'negp', "a": 10, "b": 0},
        {"op": 'negp', "a": 9, "b": 0},
        {"op": 'negp', "a": 8, "b": 0},
        {"op": 'negp', "a": 7, "b": 0},
    ],
    'pc-u2-no-long-division': [
        {"op": 'remt', "a": 2, "b": 1, "c": 3},
        {"op": 'remt', "a": 2, "b": 2, "c": 6},
        {"op": 'remt', "a": 2, "b": 4, "c": 5},
        {"op": 'remt', "a": 3, "b": 3, "c": 4},
        {"op": 'remt', "a": 4, "b": 2, "c": 3},
    ],
    'pc-u2-the-roots-secret': [
        {"op": 'vprd', "a": 2, "b": 6, "c": 0},
        {"op": 'vprd', "a": 3, "b": 7, "c": 0},
        {"op": 'vprd', "a": 3, "b": 8, "c": 0},
        {"op": 'vprd', "a": 4, "b": 7, "c": 0},
        {"op": 'vprd', "a": 4, "b": 8, "c": 0},
    ],
    'pc-u2-twice-forbidden': [
        {"op": 'vasy', "a": 3, "b": 4, "c": 0},
        {"op": 'vasy', "a": 2, "b": 7, "c": 0},
        {"op": 'vasy', "a": 3, "b": 7, "c": 0},
        {"op": 'vasy', "a": 5, "b": 6, "c": 0},
        {"op": 'vasy', "a": 6, "b": 7, "c": 0},
    ],
    'pc-u3-the-power-comes-down': [
        {"op": 'logp', "a": 64, "b": 3},
        {"op": 'logp', "a": 256, "b": 2},
        {"op": 'logp', "a": 32, "b": 3},
        {"op": 'logp', "a": 128, "b": 2},
        {"op": 'logp', "a": 16, "b": 3},
    ],
    'pc-u3-rebuild-the-number': [
        {"op": 'lsol', "a": 3, "b": 5},
        {"op": 'lsol', "a": 2, "b": 7},
        {"op": 'lsol', "a": 10, "b": 2},
        {"op": 'lsol', "a": 3, "b": 4},
        {"op": 'lsol', "a": 2, "b": 6},
    ],
    'pc-u3-count-the-halvings': [
        {"op": 'hcnt', "a": 32, "b": 4, "c": 0},
        {"op": 'hcnt', "a": 56, "b": 7, "c": 0},
        {"op": 'hcnt', "a": 96, "b": 6, "c": 0},
        {"op": 'hcnt', "a": 64, "b": 2},
        {"op": 'hcnt', "a": 80, "b": 5},
    ],
    'pc-u3-money-doubles': [
        {"op": 'cmpd', "a": 3, "b": 2, "c": 2},
        {"op": 'cmpd', "a": 4, "b": 3, "c": 2},
        {"op": 'cmpd', "a": 4, "b": 3, "c": 3},
        {"op": 'cmpd', "a": 6, "b": 3, "c": 4},
        {"op": 'cmpd', "a": 5, "b": 3, "c": 6},
    ],
    'pc-u4-the-half-turn-language': [
        {"op": 'rad1', "a": 11, "b": 0},
        {"op": 'rad1', "a": 10, "b": 0},
        {"op": 'rad1', "a": 9, "b": 0},
        {"op": 'rad1', "a": 8, "b": 0},
        {"op": 'rad1', "a": 7, "b": 0},
    ],
    'pc-u4-the-backwards-spin': [
        {"op": 'nspn', "a": 21, "b": 0, "c": 0},
        {"op": 'nspn', "a": 48, "b": 0, "c": 0},
        {"op": 'nspn', "a": 77, "b": 0, "c": 0},
        {"op": 'nspn', "a": 105, "b": 0, "c": 0},
        {"op": 'nspn', "a": 133, "b": 0, "c": 0},
    ],
    'pc-u4-hug-the-flat-line': [
        {"op": 'refq', "a": 145, "b": 0, "c": 0},
        {"op": 'refq', "a": 155, "b": 0, "c": 0},
        {"op": 'refq', "a": 170, "b": 0},
        {"op": 'refq', "a": 160, "b": 0},
        {"op": 'refq', "a": 150, "b": 0},
    ],
    'pc-u4-the-faster-wave': [
        {"op": 'wper', "a": 18, "b": 0},
        {"op": 'wper', "a": 15, "b": 0},
        {"op": 'wper', "a": 12, "b": 0},
        {"op": 'wper', "a": 10, "b": 0},
        {"op": 'wper', "a": 9, "b": 0},
    ],
    'pc-u5-one-whole-between-them': [
        {"op": 'pyid', "a": 5, "b": 0, "c": 0},
        {"op": 'pyid', "a": 22, "b": 0, "c": 0},
        {"op": 'pyid', "a": 41, "b": 0, "c": 0},
        {"op": 'pyid', "a": 58, "b": 0, "c": 0},
        {"op": 'pyid', "a": 74, "b": 0, "c": 0},
    ],
    'pc-u5-partners-across-ninety': [
        {"op": 'cofn', "a": 35, "b": 0, "c": 0},
        {"op": 'cofn', "a": 55, "b": 0, "c": 0},
        {"op": 'cofn', "a": 80, "b": 0},
        {"op": 'cofn', "a": 70, "b": 0},
        {"op": 'cofn', "a": 65, "b": 0},
    ],
    'pc-u5-the-mirror-knows': [
        {"op": 'negf', "a": 630, "b": 0, "c": 1},
        {"op": 'negf', "a": 540, "b": 0, "c": 0},
        {"op": 'negf', "a": 450, "b": 0, "c": 1},
        {"op": 'negf', "a": 360, "b": 0, "c": 0},
        {"op": 'negf', "a": 270, "b": 0, "c": 1},
    ],
    'pc-u5-count-the-crossings': [
        {"op": 'sols', "a": 0, "b": 2, "c": 1},
        {"op": 'sols', "a": 0, "b": 2, "c": 0},
        {"op": 'sols', "a": 1, "b": 2, "c": 1},
        {"op": 'sols', "a": -1, "b": 2, "c": 1},
        {"op": 'sols', "a": 1, "b": 2, "c": 0},
    ],
    'pc-u6-two-sides-and-the-angle': [
        {"op": 'arsn', "a": 2, "b": 8, "c": 30},
        {"op": 'arsn', "a": 4, "b": 6, "c": 30},
        {"op": 'arsn', "a": 8, "b": 4, "c": 30},
        {"op": 'arsn', "a": 8, "b": 5, "c": 30},
        {"op": 'arsn', "a": 6, "b": 10, "c": 30},
    ],
    'pc-u6-the-thirty-degree-ramp': [
        {"op": 'ramp', "a": 22, "b": 0, "c": 0},
        {"op": 'ramp', "a": 26, "b": 0, "c": 0},
        {"op": 'ramp', "a": 30, "b": 0, "c": 0},
        {"op": 'ramp', "a": 34, "b": 0, "c": 0},
        {"op": 'ramp', "a": 28, "b": 0},
    ],
    'pc-u6-past-the-full-turn': [
        {"op": 'brng', "a": 300, "b": 120},
        {"op": 'brng', "a": 280, "b": 130},
        {"op": 'brng', "a": 270, "b": 135},
        {"op": 'brng', "a": 260, "b": 140},
        {"op": 'brng', "a": 250, "b": 145},
    ],
    'pc-u6-the-arrow-and-its-steps': [
        {"op": 'vmag', "a": 8, "b": 6, "c": 10},
        {"op": 'vmag', "a": 5, "b": 12, "c": 13},
        {"op": 'vmag', "a": 16, "b": 30, "c": 34},
        {"op": 'vmag', "a": 18, "b": 24, "c": 30},
        {"op": 'vmag', "a": 20, "b": 21, "c": 29},
    ],
    'pc-u7-un-square-the-radius': [
        {"op": 'crad', "a": 1, "b": 1, "c": 2},
        {"op": 'crad', "a": 4, "b": 9, "c": 3},
        {"op": 'crad', "a": 3, "b": 3, "c": 5},
        {"op": 'crad', "a": 5, "b": 4, "c": 6},
        {"op": 'crad', "a": 4, "b": 9, "c": 8},
    ],
    'pc-u7-where-the-circle-sits': [
        {"op": 'cctr', "a": 2, "b": 1, "c": 2},
        {"op": 'cctr', "a": 3, "b": 4, "c": 3},
        {"op": 'cctr', "a": 4, "b": 3, "c": 4},
        {"op": 'cctr', "a": 4, "b": 10, "c": 5},
        {"op": 'cctr', "a": 5, "b": 7, "c": 6},
    ],
    'pc-u7-edge-to-edge': [
        {"op": 'elax', "a": 3, "b": 4, "c": 0},
        {"op": 'elax', "a": 4, "b": 6, "c": 0},
        {"op": 'elax', "a": 6, "b": 3, "c": 0},
        {"op": 'elax', "a": 7, "b": 8, "c": 0},
        {"op": 'elax', "a": 9, "b": 6, "c": 0},
    ],
    'pc-u7-where-you-are-at-time-t': [
        {"op": 'parm', "a": 4, "b": 3, "c": 2},
        {"op": 'parm', "a": 4, "b": 3, "c": 4},
        {"op": 'parm', "a": 4, "b": 3, "c": 5},
        {"op": 'parm', "a": 8, "b": 6, "c": 3},
        {"op": 'parm', "a": 12, "b": 5, "c": 3},
    ],
    'pc-u8-add-the-whole-run': [
        {"op": 'gsum', "a": 4, "b": 2, "c": 4},
        {"op": 'gsum', "a": 5, "b": 3, "c": 3},
        {"op": 'gsum', "a": 4, "b": 3, "c": 3},
        {"op": 'gsum', "a": 3, "b": 2, "c": 4},
        {"op": 'gsum', "a": 6, "b": 2, "c": 3},
    ],
    'pc-u8-the-instruction-called-sigma': [
        {"op": 'sigm', "a": 4, "b": 3, "c": 0},
        {"op": 'sigm', "a": 5, "b": 4, "c": 0},
        {"op": 'sigm', "a": 2, "b": 8, "c": 0},
        {"op": 'sigm', "a": 6, "b": 5, "c": 0},
        {"op": 'sigm', "a": 2, "b": 11, "c": 0},
    ],
    'pc-u8-when-order-does-not-matter': [
        {"op": 'pasc', "a": 10, "b": 2},
        {"op": 'pasc', "a": 9, "b": 2},
        {"op": 'pasc', "a": 7, "b": 3},
        {"op": 'pasc', "a": 8, "b": 2},
        {"op": 'pasc', "a": 7, "b": 2},
    ],
    'pc-u8-the-sum-that-never-ends': [
        {"op": 'gser', "a": 52, "b": 0, "c": 0},
        {"op": 'gser', "a": 44, "b": 0},
        {"op": 'gser', "a": 40, "b": 0},
        {"op": 'gser', "a": 36, "b": 0},
        {"op": 'gser', "a": 32, "b": 0},
    ],
    'pc-u9-walk-the-value-in': [
        {"op": 'lsub', "a": 2, "b": 2, "c": 3},
        {"op": 'lsub', "a": 6, "b": 2, "c": 2},
        {"op": 'lsub', "a": 6, "b": 3, "c": 2},
        {"op": 'lsub', "a": 6, "b": 4, "c": 4},
        {"op": 'lsub', "a": 7, "b": 5, "c": 3},
    ],
    'pc-u9-the-hole-in-the-curve': [
        {"op": 'lhol', "a": 5, "b": 0, "c": 0},
        {"op": 'lhol', "a": 10, "b": 0, "c": 0},
        {"op": 'lhol', "a": 13, "b": 0, "c": 0},
        {"op": 'lhol', "a": 15, "b": 0},
        {"op": 'lhol', "a": 12, "b": 0},
    ],
    'pc-u9-the-two-sides-disagree': [
        {"op": 'lsid', "a": 2, "b": 8, "c": 0},
        {"op": 'lsid', "a": 15, "b": 3, "c": 1},
        {"op": 'lsid', "a": 9, "b": 13, "c": 0},
        {"op": 'lsid', "a": 15, "b": 11, "c": 1},
        {"op": 'lsid', "a": 9, "b": 23, "c": 0},
    ],
    'pc-u9-the-shrinking-window': [
        {"op": 'avgr', "a": 1, "b": 4, "c": 0},
        {"op": 'avgr', "a": 1, "b": 7, "c": 0},
        {"op": 'avgr', "a": 1, "b": 9, "c": 0},
        {"op": 'avgr', "a": 3, "b": 8, "c": 0},
        {"op": 'avgr', "a": 3, "b": 11, "c": 0},
    ],
    'ps-u1-under-the-tallest-stack': [
        {"op": 'dotm', "a": 5, "b": 4, "c": 0},
        {"op": 'dotm', "a": 7, "b": 6, "c": 0},
        {"op": 'dotm', "a": 9, "b": 6, "c": 0},
        {"op": 'dotm', "a": 12, "b": 4, "c": 0},
        {"op": 'dotm', "a": 14, "b": 6, "c": 0},
    ],
    'ps-u1-count-the-ones-above': [
        {"op": 'dcnt', "a": 5, "b": 4, "c": 6},
        {"op": 'dcnt', "a": 17, "b": 4, "c": 8},
        {"op": 'dcnt', "a": 14, "b": 5, "c": 3},
        {"op": 'dcnt', "a": 12, "b": 6, "c": 9},
        {"op": 'dcnt', "a": 14, "b": 7, "c": 9},
    ],
    'ps-u1-add-the-bars': [
        {"op": 'htot', "a": 2, "b": 2, "c": 5},
        {"op": 'htot', "a": 2, "b": 8, "c": 2},
        {"op": 'htot', "a": 2, "b": 5, "c": 7},
        {"op": 'htot', "a": 5, "b": 3, "c": 7},
        {"op": 'htot', "a": 5, "b": 5, "c": 7},
    ],
    'ps-u1-the-one-that-sits-alone': [
        {"op": 'farv', "a": 5, "b": 18, "c": 0},
        {"op": 'farv', "a": 8, "b": 24, "c": 0},
        {"op": 'farv', "a": 6, "b": 28, "c": 0},
        {"op": 'farv', "a": 13, "b": 31, "c": 0},
        {"op": 'farv', "a": 9, "b": 35, "c": 0},
    ],
    'ps-u2-no-single-middle': [
        {"op": 'medv', "a": 2, "b": 5, "c": 0},
        {"op": 'medv', "a": 4, "b": 9, "c": 0},
        {"op": 'medv', "a": 3, "b": 13, "c": 0},
        {"op": 'medv', "a": 3, "b": 17, "c": 0},
        {"op": 'medv', "a": 3, "b": 20, "c": 0},
    ],
    'ps-u2-the-middle-half': [
        {"op": 'iqrw', "a": 5, "b": 9, "c": 3},
        {"op": 'iqrw', "a": 9, "b": 15, "c": 6},
        {"op": 'iqrw', "a": 8, "b": 18, "c": 5},
        {"op": 'iqrw', "a": 7, "b": 21, "c": 3},
        {"op": 'iqrw', "a": 6, "b": 24, "c": 2},
    ],
    'ps-u2-how-far-from-the-middle': [
        {"op": 'madv', "a": 9, "b": 2, "c": 0},
        {"op": 'madv', "a": 25, "b": 2, "c": 0},
        {"op": 'madv', "a": 23, "b": 3, "c": 0},
        {"op": 'madv', "a": 23, "b": 4, "c": 0},
        {"op": 'madv', "a": 25, "b": 5, "c": 0},
    ],
    'ps-u2-a-percent-not-a-person': [
        {"op": 'pctl', "a": 20, "b": 15, "c": 0},
        {"op": 'pctl', "a": 35, "b": 20, "c": 0},
        {"op": 'pctl', "a": 44, "b": 25, "c": 0},
        {"op": 'pctl', "a": 40, "b": 40, "c": 0},
        {"op": 'pctl', "a": 30, "b": 80, "c": 0},
    ],
    'ps-u3-one-dot-two-numbers': [
        {"op": 'spnt', "a": 2, "b": 0, "c": 4},
        {"op": 'spnt', "a": 4, "b": 0, "c": 3},
        {"op": 'spnt', "a": 6, "b": 0, "c": 2},
        {"op": 'spnt', "a": 8, "b": 0, "c": 4},
        {"op": 'spnt', "a": 12, "b": 0, "c": 3},
    ],
    'ps-u3-the-slope-is-a-rate': [
        {"op": 'sslp', "a": 3, "b": 2, "c": 0},
        {"op": 'sslp', "a": 2, "b": 7, "c": 0},
        {"op": 'sslp', "a": 4, "b": 5, "c": 0},
        {"op": 'sslp', "a": 4, "b": 7, "c": 0},
        {"op": 'sslp', "a": 6, "b": 6, "c": 0},
    ],
    'ps-u3-how-far-off-the-line': [
        {"op": 'resd', "a": 6, "b": 9, "c": 0},
        {"op": 'resd', "a": 7, "b": 17, "c": 0},
        {"op": 'resd', "a": 7, "b": 25, "c": 0},
        {"op": 'resd', "a": 7, "b": 33, "c": 0},
        {"op": 'resd', "a": 7, "b": 41, "c": 0},
    ],
    'ps-u3-through-the-middle-of-the-cloud': [
        {"op": 'sblw', "a": 8, "b": 5, "c": 0},
        {"op": 'sblw', "a": 11, "b": 3, "c": 0},
        {"op": 'sblw', "a": 14, "b": 8, "c": 0},
        {"op": 'sblw', "a": 16, "b": 10, "c": 0},
        {"op": 'sblw', "a": 18, "b": 12, "c": 0},
    ],
    'ps-u4-a-sample-that-matches': [
        {"op": 'strf', "a": 30, "b": 50, "c": 40},
        {"op": 'strf', "a": 90, "b": 75, "c": 22},
        {"op": 'strf', "a": 35, "b": 70, "c": 36},
        {"op": 'strf', "a": 50, "b": 90, "c": 28},
        {"op": 'strf', "a": 90, "b": 70, "c": 16},
    ],
    'ps-u4-who-actually-answered': [
        {"op": 'resp', "a": 30, "b": 3, "c": 0},
        {"op": 'resp', "a": 25, "b": 6, "c": 0},
        {"op": 'resp', "a": 60, "b": 18, "c": 0},
        {"op": 'resp', "a": 115, "b": 46, "c": 0},
        {"op": 'resp', "a": 80, "b": 48, "c": 0},
    ],
    'ps-u4-the-ones-you-never-asked': [
        {"op": 'bias', "a": 21, "b": 41, "c": 0},
        {"op": 'bias', "a": 27, "b": 51, "c": 0},
        {"op": 'bias', "a": 21, "b": 50, "c": 0},
        {"op": 'bias', "a": 27, "b": 60, "c": 0},
        {"op": 'bias', "a": 30, "b": 68, "c": 0},
    ],
    'ps-u4-the-price-of-accuracy': [
        {"op": 'merr', "a": 25, "b": 2, "c": 0},
        {"op": 'merr', "a": 32, "b": 2, "c": 0},
        {"op": 'merr', "a": 38, "b": 8, "c": 0},
        {"op": 'merr', "a": 45, "b": 7, "c": 0},
        {"op": 'merr', "a": 52, "b": 7, "c": 0},
    ],
    'ps-u5-chance-on-a-scale': [
        {"op": 'ppct', "a": 3, "b": 25, "c": 0},
        {"op": 'ppct', "a": 4, "b": 16, "c": 0},
        {"op": 'ppct', "a": 17, "b": 50, "c": 0},
        {"op": 'ppct', "a": 18, "b": 40, "c": 0},
        {"op": 'ppct', "a": 13, "b": 20, "c": 0},
    ],
    'ps-u5-either-one-wins': [
        {"op": 'por', "a": 2, "b": 3, "c": 3},
        {"op": 'por', "a": 3, "b": 4, "c": 9},
        {"op": 'por', "a": 6, "b": 2, "c": 9},
        {"op": 'por', "a": 3, "b": 7, "c": 7},
        {"op": 'por', "a": 5, "b": 6, "c": 9},
    ],
    'ps-u5-both-at-once': [
        {"op": 'pand', "a": 3, "b": 2, "c": 0},
        {"op": 'pand', "a": 2, "b": 9, "c": 0},
        {"op": 'pand', "a": 3, "b": 9, "c": 0},
        {"op": 'pand', "a": 5, "b": 8, "c": 0},
        {"op": 'pand', "a": 7, "b": 8, "c": 0},
    ],
    'ps-u5-count-the-winning-paths': [
        {"op": 'ptre', "a": 8, "b": 5, "c": 0},
        {"op": 'ptre', "a": 9, "b": 6, "c": 0},
        {"op": 'ptre', "a": 9, "b": 7},
        {"op": 'ptre', "a": 8, "b": 7},
        {"op": 'ptre', "a": 8, "b": 6},
    ],
    'ps-u6-out-of-how-many-now': [
        {"op": 'cbse', "a": 2, "b": 2, "c": 3},
        {"op": 'cbse', "a": 3, "b": 5, "c": 5},
        {"op": 'cbse', "a": 3, "b": 7, "c": 12},
        {"op": 'cbse', "a": 3, "b": 9, "c": 8},
        {"op": 'cbse', "a": 2, "b": 12, "c": 14},
    ],
    'ps-u6-inside-the-smaller-world': [
        {"op": 'ccnt', "a": 3, "b": 12, "c": 0},
        {"op": 'ccnt', "a": 3, "b": 7, "c": 0},
        {"op": 'ccnt', "a": 9, "b": 11, "c": 0},
        {"op": 'ccnt', "a": 9, "b": 6, "c": 0},
        {"op": 'ccnt', "a": 7, "b": 3, "c": 0},
    ],
    'ps-u6-what-independent-claims': [
        {"op": 'indp', "a": 65, "b": 45, "c": 20},
        {"op": 'indp', "a": 55, "b": 35, "c": 20},
        {"op": 'indp', "a": 50, "b": 25, "c": 20},
        {"op": 'indp', "a": 45, "b": 15, "c": 80},
        {"op": 'indp', "a": 40, "b": 30, "c": 90},
    ],
    'ps-u6-the-bag-remembers': [
        {"op": 'wout', "a": 3, "b": 6, "c": 0},
        {"op": 'wout', "a": 8, "b": 14, "c": 0},
        {"op": 'wout', "a": 11, "b": 19, "c": 0},
        {"op": 'wout', "a": 8, "b": 25, "c": 0},
        {"op": 'wout', "a": 12, "b": 31, "c": 0},
    ],
    'ps-u7-the-chances-fill-the-hundred': [
        {"op": 'pdis', "a": 35, "b": 55, "c": 0},
        {"op": 'pdis', "a": 30, "b": 50, "c": 0},
        {"op": 'pdis', "a": 10, "b": 60, "c": 0},
        {"op": 'pdis', "a": 40, "b": 25, "c": 0},
        {"op": 'pdis', "a": 20, "b": 35, "c": 0},
    ],
    'ps-u7-what-one-play-is-worth': [
        {"op": 'evwa', "a": 6, "b": 2, "c": 25},
        {"op": 'evwa', "a": 24, "b": 4, "c": 10},
        {"op": 'evwa', "a": 23, "b": 3, "c": 25},
        {"op": 'evwa', "a": 16, "b": 8, "c": 25},
        {"op": 'evwa', "a": 15, "b": 11, "c": 25},
    ],
    'ps-u7-what-would-be-fair': [
        {"op": 'fair', "a": 2, "b": 40, "c": 0},
        {"op": 'fair', "a": 6, "b": 40, "c": 0},
        {"op": 'fair', "a": 6, "b": 25, "c": 0},
        {"op": 'fair', "a": 14, "b": 40, "c": 0},
        {"op": 'fair', "a": 13, "b": 25, "c": 0},
    ],
    'ps-u7-why-the-machine-stays-open': [
        {"op": 'hedg', "a": 7, "b": 5, "c": 0},
        {"op": 'hedg', "a": 9, "b": 4, "c": 0},
        {"op": 'hedg', "a": 11, "b": 5, "c": 0},
        {"op": 'hedg', "a": 13, "b": 9, "c": 0},
        {"op": 'hedg', "a": 15, "b": 12, "c": 0},
    ],
    'ps-u8-the-crowded-middle': [
        {"op": 'n68', "a": 75, "b": 0, "c": 0},
        {"op": 'n68', "a": 150, "b": 0, "c": 0},
        {"op": 'n68', "a": 200, "b": 0, "c": 0},
        {"op": 'n68', "a": 300, "b": 0, "c": 0},
        {"op": 'n68', "a": 350, "b": 0, "c": 0},
    ],
    'ps-u8-how-far-out-is-that': [
        {"op": 'zsco', "a": 10, "b": 3, "c": 16},
        {"op": 'zsco', "a": 18, "b": 5, "c": 28},
        {"op": 'zsco', "a": 26, "b": 4, "c": 38},
        {"op": 'zsco', "a": 34, "b": 5, "c": 49},
        {"op": 'zsco', "a": 43, "b": 4, "c": 51},
    ],
    'ps-u8-which-value-sits-out-there': [
        {"op": 'zval', "a": 10, "b": 3, "c": 0},
        {"op": 'zval', "a": 20, "b": 2, "c": 0},
        {"op": 'zval', "a": 30, "b": 2, "c": 0},
        {"op": 'zval', "a": 40, "b": 2, "c": 0},
        {"op": 'zval', "a": 50, "b": 2, "c": 0},
    ],
    'ps-u8-almost-nobody-out-there': [
        {"op": 'ntal', "a": 440, "b": 0},
        {"op": 'ntal', "a": 400, "b": 0},
        {"op": 'ntal', "a": 360, "b": 0},
        {"op": 'ntal', "a": 320, "b": 0},
        {"op": 'ntal', "a": 280, "b": 0},
    ],
    'ps-u9-give-or-take': [
        {"op": 'cint', "a": 20, "b": 11, "c": 0},
        {"op": 'cint', "a": 25, "b": 12, "c": 0},
        {"op": 'cint', "a": 24, "b": 9, "c": 0},
        {"op": 'cint', "a": 20, "b": 3, "c": 0},
        {"op": 'cint', "a": 24, "b": 6, "c": 0},
    ],
    'ps-u9-how-wide-is-the-doubt': [
        {"op": 'cwid', "a": 20, "b": 2, "c": 0},
        {"op": 'cwid', "a": 25, "b": 4, "c": 0},
        {"op": 'cwid', "a": 20, "b": 7, "c": 0},
        {"op": 'cwid', "a": 20, "b": 9, "c": 0},
        {"op": 'cwid', "a": 23, "b": 11, "c": 0},
    ],
    'ps-u9-can-that-claim-survive': [
        {"op": 'inci', "a": 20, "b": 3, "c": 25},
        {"op": 'inci', "a": 21, "b": 2, "c": 28},
        {"op": 'inci', "a": 22, "b": 2, "c": 31},
        {"op": 'inci', "a": 22, "b": 2, "c": 33},
        {"op": 'inci', "a": 22, "b": 3, "c": 36},
    ],
    'ps-u9-the-range-in-real-people': [
        {"op": 'npop', "a": 35, "b": 5, "c": 300},
        {"op": 'npop', "a": 50, "b": 10, "c": 200},
        {"op": 'npop', "a": 20, "b": 5, "c": 500},
        {"op": 'npop', "a": 40, "b": 5, "c": 200},
        {"op": 'npop', "a": 20, "b": 5, "c": 400},
    ],
    'calc-u1-limits-pass-through': [
        {"op": 'llaw', "a": 2, "b": 3, "c": 0},
        {"op": 'llaw', "a": 3, "b": 4, "c": 0},
        {"op": 'llaw', "a": 2, "b": 8, "c": 0},
        {"op": 'llaw', "a": 2, "b": 10, "c": 0},
        {"op": 'llaw', "a": 11, "b": 2, "c": 0},
    ],
    'calc-u1-far-out-only-the-leaders-matter': [
        {"op": 'linf', "a": 8, "b": 4, "c": 0},
        {"op": 'linf', "a": 20, "b": 5, "c": 0},
        {"op": 'linf', "a": 30, "b": 5, "c": 0},
        {"op": 'linf', "a": 18, "b": 2, "c": 0},
        {"op": 'linf', "a": 33, "b": 3, "c": 0},
    ],
    'calc-u1-how-big-is-the-break': [
        {"op": 'jump', "a": 2, "b": 5, "c": 0},
        {"op": 'jump', "a": 2, "b": 8, "c": 0},
        {"op": 'jump', "a": 7, "b": 14, "c": 0},
        {"op": 'jump', "a": 7, "b": 16, "c": 0},
        {"op": 'jump', "a": 4, "b": 15, "c": 0},
    ],
    'calc-u1-mend-the-curve': [
        {"op": 'cfix', "a": 2, "b": 3, "c": 4},
        {"op": 'cfix', "a": 4, "b": 2, "c": 5},
        {"op": 'cfix', "a": 2, "b": 4, "c": 9},
        {"op": 'cfix', "a": 5, "b": 2, "c": 7},
        {"op": 'cfix', "a": 7, "b": 3, "c": 6},
    ],
    'calc-u2-the-window-closes': [
        {"op": 'derv', "a": 4, "b": 0, "c": 0},
        {"op": 'derv', "a": 12, "b": 0},
        {"op": 'derv', "a": 11, "b": 0},
        {"op": 'derv', "a": 10, "b": 0},
        {"op": 'derv', "a": 9, "b": 0},
    ],
    'calc-u2-the-power-comes-down-front': [
        {"op": 'pwrc', "a": 3, "b": 2, "c": 0},
        {"op": 'pwrc', "a": 2, "b": 6, "c": 0},
        {"op": 'pwrc', "a": 2, "b": 7, "c": 0},
        {"op": 'pwrc', "a": 3, "b": 6, "c": 0},
        {"op": 'pwrc', "a": 7, "b": 3, "c": 0},
    ],
    'calc-u2-a-line-has-one-slope': [
        {"op": 'cnst', "a": 2, "b": 3, "c": 0},
        {"op": 'cnst', "a": 4, "b": 7, "c": 0},
        {"op": 'cnst', "a": 7, "b": 3, "c": 0},
        {"op": 'cnst', "a": 9, "b": 4, "c": 0},
        {"op": 'cnst', "a": 11, "b": 6, "c": 0},
    ],
    'calc-u2-feed-the-derivative-an-x': [
        {"op": 'evat', "a": 3, "b": 0, "c": 4},
        {"op": 'evat', "a": 4, "b": 0, "c": 3},
        {"op": 'evat', "a": 4, "b": 0, "c": 4},
        {"op": 'evat', "a": 3, "b": 0, "c": 6},
        {"op": 'evat', "a": 4, "b": 0, "c": 6},
    ],
    'calc-u3-two-things-multiplied': [
        {"op": 'prod', "a": 4, "b": 0, "c": 2},
        {"op": 'prod', "a": 2, "b": 0, "c": 4},
        {"op": 'prod', "a": 3, "b": 0, "c": 4},
        {"op": 'prod', "a": 3, "b": 0, "c": 5},
        {"op": 'prod', "a": 4, "b": 0, "c": 5},
    ],
    'calc-u3-do-not-forget-the-inside': [
        {"op": 'chan', "a": 3, "b": 2, "c": 0},
        {"op": 'chan', "a": 2, "b": 6, "c": 0},
        {"op": 'chan', "a": 2, "b": 7, "c": 0},
        {"op": 'chan', "a": 3, "b": 6, "c": 0},
        {"op": 'chan', "a": 7, "b": 3, "c": 0},
    ],
    'calc-u3-the-chain-rule-at-a-point': [
        {"op": 'chev', "a": 2, "b": 6, "c": 0},
        {"op": 'chev', "a": 5, "b": 3, "c": 0},
        {"op": 'chev', "a": 2, "b": 10, "c": 0},
        {"op": 'chev', "a": 7, "b": 3, "c": 0},
        {"op": 'chev', "a": 4, "b": 6, "c": 0},
    ],
    'calc-u3-a-number-underneath': [
        {"op": 'quot', "a": 3, "b": 3, "c": 0},
        {"op": 'quot', "a": 14, "b": 7, "c": 0},
        {"op": 'quot', "a": 28, "b": 7, "c": 0},
        {"op": 'quot', "a": 36, "b": 6, "c": 0},
        {"op": 'quot', "a": 18, "b": 2, "c": 0},
    ],
    'calc-u4-when-is-it-going-that-fast': [
        {"op": 'vsol', "a": 3, "b": 12, "c": 0},
        {"op": 'vsol', "a": 5, "b": 40, "c": 0},
        {"op": 'vsol', "a": 7, "b": 84, "c": 0},
        {"op": 'vsol', "a": 4, "b": 72, "c": 0},
        {"op": 'vsol', "a": 6, "b": 132, "c": 0},
    ],
    'calc-u4-one-rate-drives-another': [
        {"op": 'mrat', "a": 4, "b": 3, "c": 0},
        {"op": 'mrat', "a": 6, "b": 2, "c": 0},
        {"op": 'mrat', "a": 4, "b": 4, "c": 0},
        {"op": 'mrat', "a": 4, "b": 5, "c": 0},
        {"op": 'mrat', "a": 4, "b": 6, "c": 0},
    ],
    'calc-u4-where-the-curve-levels-off': [
        {"op": 'crit', "a": 6, "b": 0, "c": 0},
        {"op": 'crit', "a": 22, "b": 0},
        {"op": 'crit', "a": 20, "b": 0},
        {"op": 'crit', "a": 18, "b": 0},
        {"op": 'crit', "a": 16, "b": 0},
    ],
    'calc-u4-differentiate-twice': [
        {"op": 'acce', "a": 5, "b": 0, "c": 0},
        {"op": 'acce', "a": 11, "b": 0},
        {"op": 'acce', "a": 10, "b": 0},
        {"op": 'acce', "a": 9, "b": 0},
        {"op": 'acce', "a": 8, "b": 0},
    ],
    'calc-u5-the-best-rectangle': [
        {"op": 'optr', "a": 40, "b": 0, "c": 0},
        {"op": 'optr', "a": 52, "b": 0},
        {"op": 'optr', "a": 48, "b": 0},
        {"op": 'optr', "a": 44, "b": 0},
        {"op": 'optr', "a": 36, "b": 0},
    ],
    'calc-u5-and-how-much-ground-that-wins': [
        {"op": 'maxa', "a": 40, "b": 0, "c": 0},
        {"op": 'maxa', "a": 56, "b": 0},
        {"op": 'maxa', "a": 52, "b": 0},
        {"op": 'maxa', "a": 48, "b": 0},
        {"op": 'maxa', "a": 44, "b": 0},
    ],
    'calc-u5-equal-halves-win': [
        {"op": 'sumx', "a": 24, "b": 0},
        {"op": 'sumx', "a": 22, "b": 0},
        {"op": 'sumx', "a": 20, "b": 0},
        {"op": 'sumx', "a": 18, "b": 0},
        {"op": 'sumx', "a": 16, "b": 0},
    ],
    'calc-u5-where-the-bend-changes': [
        {"op": 'infl', "a": 60, "b": 0},
        {"op": 'infl', "a": 54, "b": 0},
        {"op": 'infl', "a": 48, "b": 0},
        {"op": 'infl', "a": 42, "b": 0},
        {"op": 'infl', "a": 36, "b": 0},
    ],
    'calc-u6-the-rule-run-backwards': [
        {"op": 'anti', "a": 6, "b": 0, "c": 0},
        {"op": 'anti', "a": 16, "b": 0, "c": 0},
        {"op": 'anti', "a": 24, "b": 0, "c": 0},
        {"op": 'anti', "a": 32, "b": 0, "c": 0},
        {"op": 'anti', "a": 38, "b": 0, "c": 0},
    ],
    'calc-u6-raise-then-divide': [
        {"op": 'antp', "a": 3, "b": 8, "c": 0},
        {"op": 'antp', "a": 7, "b": 24, "c": 0},
        {"op": 'antp', "a": 7, "b": 40, "c": 0},
        {"op": 'antp', "a": 5, "b": 42, "c": 0},
        {"op": 'antp', "a": 6, "b": 63, "c": 0},
    ],
    'calc-u6-a-whole-family': [
        {"op": 'plusc', "a": 5, "b": 3, "c": 0},
        {"op": 'plusc', "a": 17, "b": 2, "c": 0},
        {"op": 'plusc', "a": 20, "b": 5, "c": 0},
        {"op": 'plusc', "a": 16, "b": 14, "c": 0},
        {"op": 'plusc', "a": 21, "b": 14, "c": 0},
    ],
    'calc-u6-one-point-picks-one-curve': [
        {"op": 'init', "a": 3, "b": 0, "c": 2},
        {"op": 'init', "a": 9, "b": 0, "c": 4},
        {"op": 'init', "a": 20, "b": 0, "c": 4},
        {"op": 'init', "a": 3, "b": 0, "c": 7},
        {"op": 'init', "a": 8, "b": 0, "c": 8},
    ],
    'calc-u7-the-area-is-the-answer': [
        {"op": 'defi', "a": 3, "b": 2, "c": 0},
        {"op": 'defi', "a": 12, "b": 2, "c": 0},
        {"op": 'defi', "a": 7, "b": 6, "c": 0},
        {"op": 'defi', "a": 11, "b": 6, "c": 0},
        {"op": 'defi', "a": 9, "b": 11, "c": 0},
    ],
    'calc-u7-when-the-graph-is-a-ramp': [
        {"op": 'triz', "a": 26, "b": 0},
        {"op": 'triz', "a": 24, "b": 0},
        {"op": 'triz', "a": 22, "b": 0},
        {"op": 'triz', "a": 20, "b": 0},
        {"op": 'triz', "a": 18, "b": 0},
    ],
    'calc-u7-end-take-away-start': [
        {"op": 'ftc', "a": 2, "b": 4, "c": 0},
        {"op": 'ftc', "a": 4, "b": 7, "c": 0},
        {"op": 'ftc', "a": 8, "b": 11, "c": 0},
        {"op": 'ftc', "a": 4, "b": 10, "c": 0},
        {"op": 'ftc', "a": 2, "b": 11, "c": 0},
    ],
    'calc-u7-flatten-it-out': [
        {"op": 'avgv', "a": 8, "b": 4, "c": 0},
        {"op": 'avgv', "a": 12, "b": 3, "c": 0},
        {"op": 'avgv', "a": 30, "b": 5, "c": 0},
        {"op": 'avgv', "a": 96, "b": 12, "c": 0},
        {"op": 'avgv', "a": 84, "b": 7, "c": 0},
    ],
    'calc-u8-the-gap-between-two-curves': [
        {"op": 'btwn', "a": 5, "b": 2, "c": 0},
        {"op": 'btwn', "a": 17, "b": 6, "c": 0},
        {"op": 'btwn', "a": 23, "b": 8, "c": 0},
        {"op": 'btwn', "a": 30, "b": 12, "c": 0},
        {"op": 'btwn', "a": 33, "b": 11, "c": 0},
    ],
    'calc-u8-a-speed-that-climbs': [
        {"op": 'trap', "a": 2, "b": 5, "c": 2},
        {"op": 'trap', "a": 2, "b": 20, "c": 2},
        {"op": 'trap', "a": 2, "b": 7, "c": 8},
        {"op": 'trap', "a": 2, "b": 15, "c": 6},
        {"op": 'trap', "a": 3, "b": 9, "c": 12},
    ],
    'calc-u8-adding-on-to-what-was-there': [
        {"op": 'accu', "a": 2, "b": 3, "c": 3},
        {"op": 'accu', "a": 2, "b": 7, "c": 7},
        {"op": 'accu', "a": 2, "b": 4, "c": 20},
        {"op": 'accu', "a": 2, "b": 5, "c": 25},
        {"op": 'accu', "a": 2, "b": 6, "c": 32},
    ],
    'calc-u8-spin-it-into-a-solid': [
        {"op": 'revo', "a": 4, "b": 2, "c": 0},
        {"op": 'revo', "a": 3, "b": 8, "c": 0},
        {"op": 'revo', "a": 7, "b": 2, "c": 0},
        {"op": 'revo', "a": 4, "b": 9, "c": 0},
        {"op": 'revo', "a": 6, "b": 5, "c": 0},
    ],
    'calc-u9-an-equation-about-a-rate': [
        {"op": 'dfeq', "a": 7, "b": 2, "c": 2},
        {"op": 'dfeq', "a": 19, "b": 3, "c": 4},
        {"op": 'dfeq', "a": 25, "b": 2, "c": 8},
        {"op": 'dfeq', "a": 20, "b": 4, "c": 2},
        {"op": 'dfeq', "a": 27, "b": 4, "c": 3},
    ],
    'calc-u9-two-rates-at-once': [
        {"op": 'mixr', "a": 5, "b": 3, "c": 2},
        {"op": 'mixr', "a": 6, "b": 4, "c": 7},
        {"op": 'mixr', "a": 4, "b": 2, "c": 11},
        {"op": 'mixr', "a": 9, "b": 5, "c": 8},
        {"op": 'mixr', "a": 7, "b": 3, "c": 12},
    ],
    'calc-u9-when-the-rate-depends-on-the-amount': [
        {"op": 'pgrw', "a": 3, "b": 2, "c": 0},
        {"op": 'pgrw', "a": 7, "b": 4, "c": 0},
        {"op": 'pgrw', "a": 8, "b": 6, "c": 0},
        {"op": 'pgrw', "a": 9, "b": 8, "c": 0},
        {"op": 'pgrw', "a": 13, "b": 8, "c": 0},
    ],
    'calc-u9-where-the-change-stops': [
        {"op": 'eqbm', "a": 8, "b": 4, "c": 0},
        {"op": 'eqbm', "a": 21, "b": 3, "c": 0},
        {"op": 'eqbm', "a": 24, "b": 2, "c": 0},
        {"op": 'eqbm', "a": 34, "b": 2, "c": 0},
        {"op": 'eqbm', "a": 189, "b": 9, "c": 0},
    ],
    'diffeq-u1-a-dash-at-every-point': [
        {"op": 'slpf', "a": 5, "b": 2, "c": 0},
        {"op": 'slpf', "a": 14, "b": 5, "c": 0},
        {"op": 'slpf', "a": 19, "b": 6, "c": 0},
        {"op": 'slpf', "a": 20, "b": 10, "c": 0},
        {"op": 'slpf', "a": 24, "b": 11, "c": 0},
    ],
    'diffeq-u1-change-the-law-change-the-field': [
        {"op": 'slpq', "a": 3, "b": 3, "c": 0},
        {"op": 'slpq', "a": 8, "b": 24, "c": 0},
        {"op": 'slpq', "a": 8, "b": 3, "c": 0},
        {"op": 'slpq', "a": 10, "b": 21, "c": 0},
        {"op": 'slpq', "a": 12, "b": 38, "c": 0},
    ],
    'diffeq-u1-reading-the-field-backwards': [
        {"op": 'isoc', "a": 5, "b": 2, "c": 0},
        {"op": 'isoc', "a": 14, "b": 4, "c": 0},
        {"op": 'isoc', "a": 28, "b": 15, "c": 0},
        {"op": 'isoc', "a": 27, "b": 10, "c": 0},
        {"op": 'isoc', "a": 29, "b": 8, "c": 0},
    ],
    'diffeq-u1-joining-the-dashes': [
        {"op": 'fldc', "a": 2, "b": 2, "c": 3},
        {"op": 'fldc', "a": 2, "b": 2, "c": 10},
        {"op": 'fldc', "a": 2, "b": 3, "c": 11},
        {"op": 'fldc', "a": 3, "b": 12, "c": 4},
        {"op": 'fldc', "a": 2, "b": 11, "c": 7},
    ],
    'diffeq-u2-splitting-the-letters-apart': [
        {"op": 'sepv', "a": 4, "b": 8, "c": 0},
        {"op": 'sepv', "a": 8, "b": 15, "c": 0},
        {"op": 'sepv', "a": 12, "b": 14, "c": 0},
        {"op": 'sepv', "a": 12, "b": 28, "c": 0},
        {"op": 'sepv', "a": 14, "b": 31, "c": 0},
    ],
    'diffeq-u2-when-the-y-is-underneath': [
        {"op": 'sepr', "a": 3, "b": 2, "c": 2},
        {"op": 'sepr', "a": 4, "b": 4, "c": 6},
        {"op": 'sepr', "a": 4, "b": 6, "c": 8},
        {"op": 'sepr', "a": 8, "b": 3, "c": 7},
        {"op": 'sepr', "a": 8, "b": 3, "c": 10},
    ],
    'diffeq-u2-the-cooling-cup': [
        {"op": 'newt', "a": 68, "b": 22, "c": 2},
        {"op": 'newt', "a": 88, "b": 25, "c": 3},
        {"op": 'newt', "a": 94, "b": 18, "c": 4},
        {"op": 'newt', "a": 45, "b": 11, "c": 2},
        {"op": 'newt', "a": 90, "b": 30, "c": 4},
    ],
    'diffeq-u2-the-tank-of-brine': [
        {"op": 'conc', "a": 12, "b": 4, "c": 0},
        {"op": 'conc', "a": 55, "b": 11, "c": 0},
        {"op": 'conc', "a": 88, "b": 11, "c": 0},
        {"op": 'conc', "a": 143, "b": 13, "c": 0},
        {"op": 'conc', "a": 105, "b": 7, "c": 0},
    ],
    'diffeq-u3-the-crowded-pond': [
        {"op": 'logi', "a": 47, "b": 30, "c": 10},
        {"op": 'logi', "a": 37, "b": 14, "c": 7},
        {"op": 'logi', "a": 86, "b": 4, "c": 8},
        {"op": 'logi', "a": 27, "b": 15, "c": 5},
        {"op": 'logi', "a": 68, "b": 6, "c": 12},
    ],
    'diffeq-u3-where-growth-peaks': [
        {"op": 'carr', "a": 20, "b": 7, "c": 0},
        {"op": 'carr', "a": 50, "b": 19, "c": 0},
        {"op": 'carr', "a": 40, "b": 11, "c": 0},
        {"op": 'carr', "a": 48, "b": 12, "c": 0},
        {"op": 'carr', "a": 52, "b": 10, "c": 0},
    ],
    'diffeq-u3-how-big-the-peak-is': [
        {"op": 'fast', "a": 24, "b": 2, "c": 0},
        {"op": 'fast', "a": 52, "b": 2, "c": 0},
        {"op": 'fast', "a": 72, "b": 2, "c": 0},
        {"op": 'fast', "a": 48, "b": 4, "c": 0},
        {"op": 'fast', "a": 80, "b": 3, "c": 0},
    ],
    'diffeq-u3-the-one-that-pushes-away': [
        {"op": 'away', "a": 4, "b": 7, "c": 3},
        {"op": 'away', "a": 4, "b": 17, "c": 3},
        {"op": 'away', "a": 4, "b": 36, "c": 2},
        {"op": 'away', "a": 4, "b": 49, "c": 2},
        {"op": 'away', "a": 4, "b": 18, "c": 9},
    ],
    'diffeq-u4-walking-it-in-straight-steps': [
        {"op": 'eulr', "a": 3, "b": 2, "c": 0},
        {"op": 'eulr', "a": 13, "b": 3, "c": 0},
        {"op": 'eulr', "a": 13, "b": 4, "c": 0},
        {"op": 'eulr', "a": 9, "b": 5, "c": 0},
        {"op": 'eulr', "a": 28, "b": 5, "c": 0},
    ],
    'diffeq-u4-the-deal-euler-offers': [
        {"op": 'estp', "a": 20, "b": 8, "c": 2},
        {"op": 'estp', "a": 44, "b": 12, "c": 3},
        {"op": 'estp', "a": 24, "b": 12, "c": 8},
        {"op": 'estp', "a": 28, "b": 8, "c": 6},
        {"op": 'estp', "a": 48, "b": 12, "c": 7},
    ],
    'diffeq-u4-sixteen-instead-of-two': [
        {"op": 'rk4', "a": 192, "b": 0, "c": 0},
        {"op": 'rk4', "a": 208, "b": 0, "c": 0},
        {"op": 'rk4', "a": 224, "b": 0, "c": 0},
        {"op": 'rk4', "a": 256, "b": 0, "c": 0},
        {"op": 'rk4', "a": 288, "b": 0, "c": 0},
    ],
    'diffeq-u4-what-accuracy-costs': [
        {"op": 'evls', "a": 13, "b": 2, "c": 0},
        {"op": 'evls', "a": 37, "b": 5, "c": 0},
        {"op": 'evls', "a": 43, "b": 5, "c": 0},
        {"op": 'evls', "a": 49, "b": 5, "c": 0},
        {"op": 'evls', "a": 64, "b": 7, "c": 0},
    ],
    'diffeq-u5-one-number-decides': [
        {"op": 'char', "a": 4, "b": 2, "c": 0},
        {"op": 'char', "a": 10, "b": 16, "c": 0},
        {"op": 'char', "a": 11, "b": 14, "c": 0},
        {"op": 'char', "a": 11, "b": 4, "c": 0},
        {"op": 'char', "a": 14, "b": 12, "c": 0},
    ],
    'diffeq-u5-the-knife-edge': [
        {"op": 'cdmp', "a": 24, "b": 0},
        {"op": 'cdmp', "a": 22, "b": 0},
        {"op": 'cdmp', "a": 20, "b": 0},
        {"op": 'cdmp', "a": 18, "b": 0},
        {"op": 'cdmp', "a": 16, "b": 0},
    ],
    'diffeq-u5-the-spring-that-never-stops': [
        {"op": 'natf', "a": 169, "b": 0},
        {"op": 'natf', "a": 144, "b": 0},
        {"op": 'natf', "a": 121, "b": 0},
        {"op": 'natf', "a": 100, "b": 0},
        {"op": 'natf', "a": 81, "b": 0},
    ],
    'diffeq-u5-damping-slows-the-rocking': [
        {"op": 'oscf', "a": 8, "b": 25, "c": 0},
        {"op": 'oscf', "a": 6, "b": 45, "c": 0},
        {"op": 'oscf', "a": 6, "b": 73, "c": 0},
        {"op": 'oscf', "a": 6, "b": 109, "c": 0},
        {"op": 'oscf', "a": 8, "b": 160, "c": 0},
    ],
    'diffeq-u6-somebody-is-pushing': [
        {"op": 'part', "a": 2, "b": 4, "c": 0},
        {"op": 'part', "a": 3, "b": 12, "c": 0},
        {"op": 'part', "a": 2, "b": 12, "c": 0},
        {"op": 'part', "a": 2, "b": 16, "c": 0},
        {"op": 'part', "a": 2, "b": 22, "c": 0},
    ],
    'diffeq-u6-the-part-that-fades': [
        {"op": 'trns', "a": 5, "b": 2, "c": 0},
        {"op": 'trns', "a": 15, "b": 5, "c": 0},
        {"op": 'trns', "a": 28, "b": 15, "c": 0},
        {"op": 'trns', "a": 30, "b": 14, "c": 0},
        {"op": 'trns', "a": 30, "b": 10, "c": 0},
    ],
    'diffeq-u6-why-soldiers-break-step': [
        {"op": 'reso', "a": 6, "b": 2, "c": 8},
        {"op": 'reso', "a": 7, "b": 5, "c": 10},
        {"op": 'reso', "a": 8, "b": 2, "c": 48},
        {"op": 'reso', "a": 7, "b": 2, "c": 60},
        {"op": 'reso', "a": 5, "b": 3, "c": 36},
    ],
    'diffeq-u6-what-saves-the-bridge': [
        {"op": 'damp', "a": 12, "b": 3, "c": 2},
        {"op": 'damp', "a": 45, "b": 3, "c": 5},
        {"op": 'damp', "a": 70, "b": 2, "c": 7},
        {"op": 'damp', "a": 84, "b": 4, "c": 3},
        {"op": 'damp', "a": 60, "b": 3, "c": 2},
    ],
    'diffeq-u7-derivatives-become-timesing': [
        {"op": 'lder', "a": 3, "b": 2, "c": 3},
        {"op": 'lder', "a": 3, "b": 7, "c": 3},
        {"op": 'lder', "a": 2, "b": 7, "c": 5},
        {"op": 'lder', "a": 2, "b": 9, "c": 6},
        {"op": 'lder', "a": 2, "b": 6, "c": 14},
    ],
    'diffeq-u7-and-now-it-is-just-algebra': [
        {"op": 'lalg', "a": 2, "b": 16, "c": 6},
        {"op": 'lalg', "a": 5, "b": 48, "c": 3},
        {"op": 'lalg', "a": 3, "b": 99, "c": 6},
        {"op": 'lalg', "a": 3, "b": 153, "c": 6},
        {"op": 'lalg', "a": 2, "b": 144, "c": 4},
    ],
    'diffeq-u7-the-shift-rule': [
        {"op": 'lshf', "a": 5, "b": 2, "c": 0},
        {"op": 'lshf', "a": 18, "b": 3, "c": 0},
        {"op": 'lshf', "a": 25, "b": 3, "c": 0},
        {"op": 'lshf', "a": 24, "b": 10, "c": 0},
        {"op": 'lshf', "a": 34, "b": 4, "c": 0},
    ],
    'diffeq-u7-reading-the-ending': [
        {"op": 'lfin', "a": 4, "b": 8, "c": 0},
        {"op": 'lfin', "a": 8, "b": 56, "c": 0},
        {"op": 'lfin', "a": 6, "b": 78, "c": 0},
        {"op": 'lfin', "a": 3, "b": 57, "c": 0},
        {"op": 'lfin', "a": 6, "b": 150, "c": 0},
    ],
    'diffeq-u8-two-things-at-once': [
        {"op": 'sysx', "a": 2, "b": 3, "c": 3},
        {"op": 'sysx', "a": 2, "b": 8, "c": 4},
        {"op": 'sysx', "a": 2, "b": 15, "c": 14},
        {"op": 'sysx', "a": 2, "b": 15, "c": 10},
        {"op": 'sysx', "a": 2, "b": 14, "c": 3},
    ],
    'diffeq-u8-where-an-arrow-goes-flat': [
        {"op": 'nucl', "a": 3, "b": 2, "c": 0},
        {"op": 'nucl', "a": 8, "b": 3, "c": 0},
        {"op": 'nucl', "a": 4, "b": 11, "c": 0},
        {"op": 'nucl', "a": 5, "b": 13, "c": 0},
        {"op": 'nucl', "a": 6, "b": 16, "c": 0},
    ],
    'diffeq-u8-the-number-in-the-corner': [
        {"op": 'detm', "a": 3, "b": 2, "c": 2},
        {"op": 'detm', "a": 4, "b": 3, "c": 6},
        {"op": 'detm', "a": 4, "b": 2, "c": 7},
        {"op": 'detm', "a": 3, "b": 2, "c": 13},
        {"op": 'detm', "a": 5, "b": 5, "c": 15},
    ],
    'diffeq-u8-two-numbers-decide-the-picture': [
        {"op": 'eign', "a": 5, "b": 2, "c": 0},
        {"op": 'eign', "a": 15, "b": 5, "c": 0},
        {"op": 'eign', "a": 28, "b": 15, "c": 0},
        {"op": 'eign', "a": 30, "b": 14, "c": 0},
        {"op": 'eign', "a": 31, "b": 11, "c": 0},
    ],
    'diffeq-u9-up-close-it-is-a-line': [
        {"op": 'lnrz', "a": 9, "b": 3, "c": 2},
        {"op": 'lnrz', "a": 36, "b": 6, "c": 2},
        {"op": 'lnrz', "a": 9, "b": 3, "c": 6},
        {"op": 'lnrz', "a": 9, "b": 3, "c": 9},
        {"op": 'lnrz', "a": 16, "b": 4, "c": 9},
    ],
    'diffeq-u9-rabbits-and-foxes': [
        {"op": 'prey', "a": 2, "b": 5, "c": 5},
        {"op": 'prey', "a": 3, "b": 8, "c": 16},
        {"op": 'prey', "a": 3, "b": 9, "c": 33},
        {"op": 'prey', "a": 3, "b": 9, "c": 48},
        {"op": 'prey', "a": 3, "b": 6, "c": 48},
    ],
    'diffeq-u9-round-and-round': [
        {"op": 'cycl', "a": 12, "b": 0, "c": 0},
        {"op": 'cycl', "a": 44, "b": 0, "c": 0},
        {"op": 'cycl', "a": 76, "b": 0, "c": 0},
        {"op": 'cycl', "a": 108, "b": 0, "c": 0},
        {"op": 'cycl', "a": 144, "b": 0, "c": 0},
    ],
    'diffeq-u9-a-perfectly-known-equation': [
        {"op": 'chao', "a": 2, "b": 3, "c": 2},
        {"op": 'chao', "a": 3, "b": 2, "c": 4},
        {"op": 'chao', "a": 7, "b": 2, "c": 3},
        {"op": 'chao', "a": 5, "b": 4, "c": 2},
        {"op": 'chao', "a": 7, "b": 2, "c": 4},
    ],
}

# I did no harm and this file is not truncated.
